/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as KbIndexRouteImport } from './routes/kb/index'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as ModelsImportRouteImport } from './routes/models/import'
import { Route as KbKbIdChatRouteImport } from './routes/kb/$kbId/chat'
import { Route as ComputeInstancesInstanceIdRouteRouteImport } from './routes/compute/instances/$instanceId/route'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsImportRoute = ModelsImportRouteImport.update({
  id: '/models/import',
  path: '/models/import',
  getParentRoute: () => rootRouteImport,
} as any)
const KbKbIdChatRoute = KbKbIdChatRouteImport.update({
  id: '/kb/$kbId/chat',
  path: '/kb/$kbId/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeInstancesInstanceIdRouteRoute =
  ComputeInstancesInstanceIdRouteRouteImport.update({
    id: '/compute/instances/$instanceId',
    path: '/compute/instances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/usage': typeof UsageRoute
  '/models/import': typeof ModelsImportRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/kb/': typeof KbIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/compute/instances/$instanceId': typeof ComputeInstancesInstanceIdRouteRoute
  '/kb/$kbId/chat': typeof KbKbIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/usage': typeof UsageRoute
  '/models/import': typeof ModelsImportRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/kb': typeof KbIndexRoute
  '/models': typeof ModelsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/compute/instances/$instanceId': typeof ComputeInstancesInstanceIdRouteRoute
  '/kb/$kbId/chat': typeof KbKbIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/usage': typeof UsageRoute
  '/models/import': typeof ModelsImportRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/kb/': typeof KbIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/compute/instances/$instanceId': typeof ComputeInstancesInstanceIdRouteRoute
  '/kb/$kbId/chat': typeof KbKbIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registry'
    | '/usage'
    | '/models/import'
    | '/settings/api-keys'
    | '/kb/'
    | '/models/'
    | '/settings/'
    | '/compute/instances/$instanceId'
    | '/kb/$kbId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registry'
    | '/usage'
    | '/models/import'
    | '/settings/api-keys'
    | '/kb'
    | '/models'
    | '/settings'
    | '/compute/instances/$instanceId'
    | '/kb/$kbId/chat'
  id:
    | '__root__'
    | '/'
    | '/registry'
    | '/usage'
    | '/models/import'
    | '/settings/api-keys'
    | '/kb/'
    | '/models/'
    | '/settings/'
    | '/compute/instances/$instanceId'
    | '/kb/$kbId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRoute: typeof RegistryRoute
  UsageRoute: typeof UsageRoute
  ModelsImportRoute: typeof ModelsImportRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  KbIndexRoute: typeof KbIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ComputeInstancesInstanceIdRouteRoute: typeof ComputeInstancesInstanceIdRouteRoute
  KbKbIdChatRoute: typeof KbKbIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/': {
      id: '/kb/'
      path: '/kb'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/import': {
      id: '/models/import'
      path: '/models/import'
      fullPath: '/models/import'
      preLoaderRoute: typeof ModelsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/$kbId/chat': {
      id: '/kb/$kbId/chat'
      path: '/kb/$kbId/chat'
      fullPath: '/kb/$kbId/chat'
      preLoaderRoute: typeof KbKbIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute/instances/$instanceId': {
      id: '/compute/instances/$instanceId'
      path: '/compute/instances/$instanceId'
      fullPath: '/compute/instances/$instanceId'
      preLoaderRoute: typeof ComputeInstancesInstanceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRoute,
  UsageRoute: UsageRoute,
  ModelsImportRoute: ModelsImportRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  KbIndexRoute: KbIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ComputeInstancesInstanceIdRouteRoute: ComputeInstancesInstanceIdRouteRoute,
  KbKbIdChatRoute: KbKbIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
