// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

import "testing"

func TestSDKAlphaSmoke(t *testing.T) {
	client := NewClient("", "token")
	if client.BaseURL == "" || Title == "" || Version == "" {
		t.Fatalf("invalid SDK metadata")
	}
	if len(Schemas) == 0 {
		t.Fatalf("expected generated schemas")
	}
	if len(Operations) == 0 {
		t.Fatalf("expected generated operations")
	}
	if !HasOperation("listAPIKeys") {
		t.Fatalf("missing expected operation")
	}

}
