// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const Layer = "core"
const Title = "KuberCloud ANI Core API"
const Version = "1.0.0"
const ServerURL = "https://{host}/api/v1"

var Operations = []string{
	"listAPIKeys",
	"createAPIKey",
	"revokeAPIKey",
	"logout",
	"beginOIDCLogin",
	"postAuthRefresh",
	"completeOIDCLogin",
	"getBranding",
	"listStorageBuckets",
	"createStorageBucket",
	"listEncryptionKeys",
	"createEncryptionKey",
	"deleteEncryptionKey",
	"getEncryptionKey",
	"revokeEncryptionKey",
	"rotateEncryptionKey",
	"sealEncryptionObject",
	"createEncryptionUnsealToken",
	"listStorageFilesystems",
	"createStorageFilesystem",
	"deleteStorageFilesystem",
	"getStorageFilesystem",
	"listFilesystemMountTargets",
	"listGPUInventory",
	"getGPUOccupancy",
	"liveness",
	"getInstanceOperation",
	"listInstances",
	"createInstance",
	"getInstance",
	"createInstanceConsoleSession",
	"listInstanceEvents",
	"createInstanceExecSession",
	"applyInstanceLifecycle",
	"listInstanceLogs",
	"getInstanceMetrics",
	"listInstanceOperations",
	"listInstanceSecurityEvents",
	"listK8sClusters",
	"createK8sCluster",
	"deleteK8sCluster",
	"getK8sCluster",
	"getK8sClusterKubeconfig",
	"listK8sClusterNodePools",
	"createK8sClusterNodePool",
	"deleteK8sClusterNodePool",
	"getK8sClusterNodePool",
	"updateK8sClusterNodePool",
	"proxyK8sClusterAPI",
	"upgradeK8sCluster",
	"listK8sClusterWorkloads",
	"reportTokenUsage",
	"getMeteringUsage",
	"listNetworkLoadBalancers",
	"createNetworkLoadBalancer",
	"deleteNetworkLoadBalancer",
	"getNetworkLoadBalancer",
	"listNetworkRoutes",
	"createNetworkRoute",
	"listNetworkSecurityGroups",
	"createNetworkSecurityGroup",
	"deleteNetworkSecurityGroup",
	"getNetworkSecurityGroup",
	"listNetworkSubnets",
	"createNetworkSubnet",
	"deleteNetworkSubnet",
	"getNetworkSubnet",
	"listNetworkVPCs",
	"createNetworkVPC",
	"deleteNetworkVPC",
	"getNetworkVPC",
	"listStorageObjects",
	"createStorageObject",
	"uploadStorageObject",
	"deleteStorageObject",
	"getStorageObject",
	"downloadStorageObject",
	"listObservabilityAlertRules",
	"createObservabilityAlertRule",
	"deleteObservabilityAlertRule",
	"getObservabilityAlertRule",
	"updateObservabilityAlertRule",
	"queryObservability",
	"readiness",
	"getRegistryImageScanResult",
	"listRegistryProjects",
	"createRegistryProject",
	"createRegistryProjectPullSecret",
	"listRegistryRepositories",
	"listRegistryArtifacts",
	"setRegistryRepositoryPermission",
	"getRegistryProjectScanReport",
	"listSandboxTemplates",
	"listSecrets",
	"createSecret",
	"deleteSecret",
	"getSecret",
	"bindSecret",
	"getTasksTaskId",
	"listVectorStores",
	"createVectorStore",
	"deleteVectorStore",
	"getVectorStore",
	"insertVectorStoreDocuments",
	"searchVectorStore",
	"listStorageVolumes",
	"createStorageVolume",
	"deleteStorageVolume",
	"getStorageVolume",
	"listVolumeSnapshots",
	"createVolumeSnapshot",
}
var Paths = []string{
	"GET /auth/api-keys",
	"POST /auth/api-keys",
	"DELETE /auth/api-keys/{key_id}",
	"POST /auth/logout",
	"POST /auth/oidc/begin",
	"POST /auth/refresh",
	"POST /auth/token",
	"GET /branding",
	"GET /buckets",
	"POST /buckets",
	"GET /encryption/keys",
	"POST /encryption/keys",
	"DELETE /encryption/keys/{key_id}",
	"GET /encryption/keys/{key_id}",
	"POST /encryption/keys/{key_id}/revoke",
	"POST /encryption/keys/{key_id}/rotate",
	"POST /encryption/seal",
	"POST /encryption/unseal-token",
	"GET /filesystems",
	"POST /filesystems",
	"DELETE /filesystems/{filesystem_id}",
	"GET /filesystems/{filesystem_id}",
	"GET /filesystems/{filesystem_id}/mount-targets",
	"GET /gpu-inventory",
	"GET /gpu-inventory/occupancy",
	"GET /healthz",
	"GET /instance-operations/{operation_id}",
	"GET /instances",
	"POST /instances",
	"GET /instances/{instance_id}",
	"POST /instances/{instance_id}/console",
	"GET /instances/{instance_id}/events",
	"POST /instances/{instance_id}/exec",
	"POST /instances/{instance_id}/lifecycle",
	"GET /instances/{instance_id}/logs",
	"GET /instances/{instance_id}/metrics",
	"GET /instances/{instance_id}/operations",
	"GET /instances/{instance_id}/security-events",
	"GET /k8s-clusters",
	"POST /k8s-clusters",
	"DELETE /k8s-clusters/{cluster_id}",
	"GET /k8s-clusters/{cluster_id}",
	"GET /k8s-clusters/{cluster_id}/kubeconfig",
	"GET /k8s-clusters/{cluster_id}/node-pools",
	"POST /k8s-clusters/{cluster_id}/node-pools",
	"DELETE /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
	"GET /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
	"PATCH /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
	"POST /k8s-clusters/{cluster_id}/proxy",
	"POST /k8s-clusters/{cluster_id}/upgrade",
	"GET /k8s-clusters/{cluster_id}/workloads",
	"POST /metering/token-usage",
	"GET /metering/usage",
	"GET /networks/load-balancers",
	"POST /networks/load-balancers",
	"DELETE /networks/load-balancers/{load_balancer_id}",
	"GET /networks/load-balancers/{load_balancer_id}",
	"GET /networks/routes",
	"POST /networks/routes",
	"GET /networks/security-groups",
	"POST /networks/security-groups",
	"DELETE /networks/security-groups/{security_group_id}",
	"GET /networks/security-groups/{security_group_id}",
	"GET /networks/subnets",
	"POST /networks/subnets",
	"DELETE /networks/subnets/{subnet_id}",
	"GET /networks/subnets/{subnet_id}",
	"GET /networks/vpcs",
	"POST /networks/vpcs",
	"DELETE /networks/vpcs/{vpc_id}",
	"GET /networks/vpcs/{vpc_id}",
	"GET /objects",
	"POST /objects",
	"POST /objects/upload",
	"DELETE /objects/{object_id}",
	"GET /objects/{object_id}",
	"GET /objects/{object_id}/download",
	"GET /observability/alert-rules",
	"POST /observability/alert-rules",
	"DELETE /observability/alert-rules/{rule_id}",
	"GET /observability/alert-rules/{rule_id}",
	"PATCH /observability/alert-rules/{rule_id}",
	"GET /observability/query",
	"GET /readyz",
	"GET /registry/images/scan-result",
	"GET /registry/projects",
	"POST /registry/projects",
	"POST /registry/projects/{project}/pull-secret",
	"GET /registry/projects/{project}/repositories",
	"GET /registry/projects/{project}/repositories/{repository}/artifacts",
	"POST /registry/projects/{project}/repositories/{repository}/permissions",
	"GET /registry/projects/{project}/scan-report",
	"GET /sandbox-templates",
	"GET /secrets",
	"POST /secrets",
	"DELETE /secrets/{secret_id}",
	"GET /secrets/{secret_id}",
	"POST /secrets/{secret_id}/bindings",
	"GET /tasks/{task_id}",
	"GET /vector-stores",
	"POST /vector-stores",
	"DELETE /vector-stores/{vector_store_id}",
	"GET /vector-stores/{vector_store_id}",
	"POST /vector-stores/{vector_store_id}/documents",
	"POST /vector-stores/{vector_store_id}/search",
	"GET /volumes",
	"POST /volumes",
	"DELETE /volumes/{volume_id}",
	"GET /volumes/{volume_id}",
	"GET /volumes/{volume_id}/snapshots",
	"POST /volumes/{volume_id}/snapshots",
}
var Schemas = []string{
	"APIKeyInfo",
	"AsyncTask",
	"BeginOIDCLoginRequest",
	"BeginOIDCLoginResponse",
	"CompleteOIDCLoginRequest",
	"CoreDevProfileInfo",
	"CreateAPIKeyRequest",
	"CreateAPIKeyResponse",
	"CreateInstanceConsoleSessionRequest",
	"CreateInstanceExecSessionRequest",
	"CreateInstanceRequest",
	"CreateInstanceResponse",
	"CreateNetworkLoadBalancerRequest",
	"CreateNetworkRouteRequest",
	"CreateNetworkSecurityGroupRequest",
	"CreateNetworkSubnetRequest",
	"CreateNetworkVPCRequest",
	"CreateObservabilityAlertRuleRequest",
	"CreateRegistryProjectRequest",
	"CreateRegistryPullSecretRequest",
	"CreateStorageBucketRequest",
	"CreateStorageFilesystemRequest",
	"CreateStorageObjectRequest",
	"CreateStorageVolumeRequest",
	"CreateVectorStoreRequest",
	"CreateVolumeSnapshotRequest",
	"CursorPage",
	"EncryptionKey",
	"EncryptionKeyCreateRequest",
	"EncryptionKeyListResponse",
	"EncryptionKeyRevokeRequest",
	"EncryptionKeyRotateRequest",
	"EncryptionKeyRotationResponse",
	"EncryptionSealRequest",
	"EncryptionSealResponse",
	"EncryptionUnsealTokenRequest",
	"EncryptionUnsealTokenResponse",
	"ErrorResponse",
	"FilesystemMountTarget",
	"FilesystemMountTargetListResponse",
	"GPUInventoryListResponse",
	"GPUInventoryRecord",
	"GPUOccupancyStats",
	"HealthCheck",
	"InstanceConsoleSession",
	"InstanceEvent",
	"InstanceEventListResponse",
	"InstanceExecSession",
	"InstanceLifecycleRequest",
	"InstanceLifecycleResponse",
	"InstanceListResponse",
	"InstanceLogEntry",
	"InstanceLogListResponse",
	"InstanceMetrics",
	"InstanceOperation",
	"InstanceRecord",
	"InstanceSecurityEvent",
	"InstanceSecurityEventListResponse",
	"K8sCluster",
	"K8sClusterCreateRequest",
	"K8sClusterKubeconfig",
	"K8sClusterListResponse",
	"K8sClusterNodePool",
	"K8sClusterNodePoolCreateRequest",
	"K8sClusterNodePoolGPU",
	"K8sClusterNodePoolListResponse",
	"K8sClusterNodePoolUpdateRequest",
	"K8sClusterProxyRequest",
	"K8sClusterProxyResponse",
	"K8sClusterUpgradeRequest",
	"K8sClusterWorkload",
	"K8sClusterWorkloadListResponse",
	"ListAPIKeysResponse",
	"LogoutRequest",
	"MeteringUsageRecord",
	"MeteringUsageResponse",
	"NetworkLoadBalancer",
	"NetworkLoadBalancerListResponse",
	"NetworkLoadBalancerListener",
	"NetworkResourceState",
	"NetworkRoute",
	"NetworkRouteListResponse",
	"NetworkSecurityGroup",
	"NetworkSecurityGroupListResponse",
	"NetworkSecurityGroupRule",
	"NetworkSubnet",
	"NetworkSubnetListResponse",
	"NetworkVPC",
	"NetworkVPCListResponse",
	"ObservabilityAlertRule",
	"ObservabilityAlertRuleListResponse",
	"ObservabilityQueryResponse",
	"RefreshAccessTokenRequest",
	"RefreshAccessTokenResponse",
	"RegistryArtifact",
	"RegistryArtifactListResponse",
	"RegistryPermission",
	"RegistryProject",
	"RegistryProjectListResponse",
	"RegistryProjectScanReport",
	"RegistryPullSecret",
	"RegistryRepository",
	"RegistryRepositoryListResponse",
	"RegistryScanResult",
	"ReportTokenUsageRequest",
	"RevokeStatusResponse",
	"SandboxConfig",
	"SandboxInstanceStatus",
	"SandboxNetworkEgressPolicy",
	"SandboxTemplate",
	"SandboxTemplateListResponse",
	"Secret",
	"SecretBinding",
	"SecretBindingRequest",
	"SecretCreateRequest",
	"SecretListResponse",
	"SetRegistryPermissionRequest",
	"StorageBucketListResponse",
	"StorageBucketRecord",
	"StorageFilesystem",
	"StorageFilesystemListResponse",
	"StorageObject",
	"StorageObjectDownloadInfo",
	"StorageObjectListResponse",
	"StorageObjectUploadRequest",
	"StorageObjectUploadResponse",
	"StorageResourceState",
	"StorageVolume",
	"StorageVolumeListResponse",
	"TokenPairResponse",
	"TokenUsageReport",
	"UpdateObservabilityAlertRuleRequest",
	"VectorStore",
	"VectorStoreDocumentInsertRequest",
	"VectorStoreDocumentInsertResponse",
	"VectorStoreListResponse",
	"VectorStoreSearchHit",
	"VectorStoreSearchRequest",
	"VectorStoreSearchResponse",
	"VectorStoreState",
	"VolumeSnapshotListResponse",
	"VolumeSnapshotRecord",
	"WorkloadIdentityBinding",
}
var IdempotencyOperations = []string{
	"createStorageBucket",
	"createEncryptionKey",
	"revokeEncryptionKey",
	"rotateEncryptionKey",
	"sealEncryptionObject",
	"createStorageFilesystem",
	"createInstance",
	"createInstanceExecSession",
	"applyInstanceLifecycle",
	"createK8sCluster",
	"createK8sClusterNodePool",
	"updateK8sClusterNodePool",
	"proxyK8sClusterAPI",
	"upgradeK8sCluster",
	"reportTokenUsage",
	"createNetworkLoadBalancer",
	"createNetworkRoute",
	"createNetworkSecurityGroup",
	"createNetworkSubnet",
	"createNetworkVPC",
	"createStorageObject",
	"uploadStorageObject",
	"createObservabilityAlertRule",
	"updateObservabilityAlertRule",
	"createRegistryProject",
	"createRegistryProjectPullSecret",
	"setRegistryRepositoryPermission",
	"createSecret",
	"createVectorStore",
	"insertVectorStoreDocuments",
	"createStorageVolume",
	"createVolumeSnapshot",
}
var CursorPaginationOperations = []string{
	"listStorageBuckets",
	"listEncryptionKeys",
	"listStorageFilesystems",
	"listFilesystemMountTargets",
	"listGPUInventory",
	"listInstances",
	"listInstanceLogs",
	"listInstanceOperations",
	"listK8sClusters",
	"listK8sClusterWorkloads",
	"listNetworkLoadBalancers",
	"listNetworkRoutes",
	"listNetworkSecurityGroups",
	"listNetworkSubnets",
	"listNetworkVPCs",
	"listStorageObjects",
	"listObservabilityAlertRules",
	"listRegistryProjects",
	"listRegistryRepositories",
	"listRegistryArtifacts",
	"listSandboxTemplates",
	"listSecrets",
	"listVectorStores",
	"listStorageVolumes",
	"listVolumeSnapshots",
}
var ErrorCodes = []string{
	"BAD_REQUEST",
	"CONFLICT",
	"FORBIDDEN",
	"INTERNAL_ERROR",
	"NOT_FOUND",
	"NOT_IMPLEMENTED",
	"PRECONDITION_FAILED",
	"RATE_LIMIT_EXCEEDED",
	"UNAUTHORIZED",
}

type APIError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Details   map[string]any `json:"details,omitempty"`
}

func (err APIError) Error() string {
	if err.Message == "" {
		return err.Code
	}
	if err.Code == "" {
		return err.Message
	}
	return err.Code + ": " + err.Message
}

type Client struct {
	BaseURL string
	Token   string
}

type RequestOptions struct {
	Body    map[string]any
	Params  map[string]string
	Headers map[string]string
}

func NewClient(baseURL string, token string) Client {
	if baseURL == "" {
		baseURL = ServerURL
	}
	return Client{BaseURL: baseURL, Token: token}
}

func (client Client) Request(method string, path string, options RequestOptions) (any, error) {
	requestURL, err := client.requestURL(path, options.Params)
	if err != nil {
		return nil, err
	}
	var body io.Reader
	if options.Body != nil {
		payload, err := json.Marshal(options.Body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		body = bytes.NewReader(payload)
	}
	req, err := http.NewRequest(strings.ToUpper(method), requestURL, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if client.Token != "" {
		req.Header.Set("Authorization", "Bearer "+client.Token)
	}
	for key, value := range options.Headers {
		req.Header.Set(key, value)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return decodeResponse(resp)
}

func (client Client) requestURL(path string, params map[string]string) (string, error) {
	base := strings.TrimRight(client.BaseURL, "/")
	relative := "/" + strings.TrimLeft(path, "/")
	parsed, err := url.Parse(base + relative)
	if err != nil {
		return "", err
	}
	query := parsed.Query()
	for key, value := range params {
		if value != "" {
			query.Set(key, value)
		}
	}
	parsed.RawQuery = query.Encode()
	return parsed.String(), nil
}

func decodeResponse(resp *http.Response) (any, error) {
	if resp.StatusCode == http.StatusNoContent {
		return nil, nil
	}
	payload, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(payload) == 0 {
		if resp.StatusCode >= 400 {
			return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
		}
		return nil, nil
	}
	var decoded any
	if strings.Contains(resp.Header.Get("Content-Type"), "application/json") {
		if err := json.Unmarshal(payload, &decoded); err != nil {
			return nil, err
		}
	} else {
		decoded = string(payload)
	}
	if resp.StatusCode >= 400 {
		if data, ok := decoded.(map[string]any); ok {
			code, _ := data["code"].(string)
			message, _ := data["message"].(string)
			requestID, _ := data["request_id"].(string)
			details, _ := data["details"].(map[string]any)
			if code != "" && message != "" {
				return nil, APIError{Code: code, Message: message, RequestID: requestID, Details: details}
			}
		}
		return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
	}
	return decoded, nil
}

func HasOperation(operationID string) bool {
	for _, operation := range Operations {
		if operation == operationID {
			return true
		}
	}
	return false
}

func NewIdempotencyKey(prefix string) (string, error) {
	if prefix == "" {
		prefix = "ani"
	}
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	return prefix + "_" + hex.EncodeToString(random), nil
}

func WithIdempotencyKey(body map[string]any, key string) (map[string]any, error) {
	if body == nil {
		body = map[string]any{}
	}
	if key == "" {
		generated, err := NewIdempotencyKey("ani")
		if err != nil {
			return nil, err
		}
		key = generated
	}
	body["idempotency_key"] = key
	return body, nil
}

func CursorParams(limit int, cursor string) map[string]string {
	params := map[string]string{}
	if limit > 0 {
		params["limit"] = fmt.Sprintf("%d", limit)
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	return params
}

func IsAPIErrorCode(code string) bool {
	for _, item := range ErrorCodes {
		if item == code {
			return true
		}
	}
	return false
}

func NewAPIError(code string, message string, requestID string, details map[string]any) APIError {
	return APIError{Code: code, Message: message, RequestID: requestID, Details: details}
}
