// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
export const layer = "services";
export const title = "KuberCloud ANI Services API";
export const version = "1.0.0";
export const serverURL = "https://{host}/api/v1/svc";
export const operations = [
  "listInferenceServices",
  "createInferenceService",
  "deleteInferenceService",
  "getInferenceService",
  "listKnowledgeBases",
  "createKnowledgeBase",
  "deleteKnowledgeBase",
  "getKnowledgeBase",
  "listKnowledgeBaseDocuments",
  "uploadKnowledgeBaseDocument",
  "deleteKnowledgeBaseDocument",
  "queryKnowledgeBase",
  "streamQueryKnowledgeBase",
  "listModels",
  "createModel",
  "importModel",
  "deleteModel",
  "getModel",
  "createModelVersion"
];
export const paths = [
  "GET /inference-services",
  "POST /inference-services",
  "DELETE /inference-services/{service_id}",
  "GET /inference-services/{service_id}",
  "GET /knowledge-bases",
  "POST /knowledge-bases",
  "DELETE /knowledge-bases/{kb_id}",
  "GET /knowledge-bases/{kb_id}",
  "GET /knowledge-bases/{kb_id}/documents",
  "POST /knowledge-bases/{kb_id}/documents",
  "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
  "POST /knowledge-bases/{kb_id}/query",
  "GET /knowledge-bases/{kb_id}/query/stream",
  "GET /models",
  "POST /models",
  "POST /models/import",
  "DELETE /models/{model_id}",
  "GET /models/{model_id}",
  "POST /models/{model_id}/versions"
];
export const schemas = [
  "AsyncTask",
  "CreateInferenceEndpointRequest",
  "CreateModelRequest",
  "CursorPage",
  "ErrorResponse",
  "InferenceEndpoint",
  "InferenceService",
  "KBDocument",
  "KBQueryRequest",
  "KBQueryResponse",
  "KnowledgeBase",
  "Model",
  "ModelVersion"
];

export class Client {
  constructor(options = {}) {
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }

  hasOperation(operationID) {
    return operations.includes(operationID);
  }
}
