// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
export const layer = "services" as const;
export const title = "KuberCloud ANI Services API" as const;
export const version = "1.0.0" as const;
export const serverURL = "https://{host}/api/v1/svc" as const;
export const operations = [
  "listInferenceServices",
  "createInferenceService",
  "deleteInferenceService",
  "getInferenceService",
  "listKnowledgeBases",
  "createKnowledgeBase",
  "deleteKnowledgeBase",
  "getKnowledgeBase",
  "listKnowledgeBaseDocuments",
  "uploadKnowledgeBaseDocument",
  "deleteKnowledgeBaseDocument",
  "queryKnowledgeBase",
  "streamQueryKnowledgeBase",
  "listModels",
  "createModel",
  "importModel",
  "deleteModel",
  "getModel",
  "createModelVersion"
] as const;
export const paths = [
  "GET /inference-services",
  "POST /inference-services",
  "DELETE /inference-services/{service_id}",
  "GET /inference-services/{service_id}",
  "GET /knowledge-bases",
  "POST /knowledge-bases",
  "DELETE /knowledge-bases/{kb_id}",
  "GET /knowledge-bases/{kb_id}",
  "GET /knowledge-bases/{kb_id}/documents",
  "POST /knowledge-bases/{kb_id}/documents",
  "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
  "POST /knowledge-bases/{kb_id}/query",
  "GET /knowledge-bases/{kb_id}/query/stream",
  "GET /models",
  "POST /models",
  "POST /models/import",
  "DELETE /models/{model_id}",
  "GET /models/{model_id}",
  "POST /models/{model_id}/versions"
] as const;
export const schemas = [
  "AsyncTask",
  "CreateInferenceEndpointRequest",
  "CreateModelRequest",
  "CursorPage",
  "ErrorResponse",
  "InferenceEndpoint",
  "InferenceService",
  "KBDocument",
  "KBQueryRequest",
  "KBQueryResponse",
  "KnowledgeBase",
  "Model",
  "ModelVersion"
] as const;

export interface ClientOptions {
  baseURL?: string;
  token?: string;
}

export class Client {
  readonly baseURL: string;
  readonly token?: string;

  constructor(options: ClientOptions = {}) {
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }

  hasOperation(operationID: string): boolean {
    return operations.includes(operationID as typeof operations[number]);
  }
}
