# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import kubercloud_ani_services as sdk

client = sdk.Client(token="token")
assert client.base_url
assert sdk.TITLE
assert sdk.VERSION
assert sdk.SCHEMAS
assert sdk.OPERATIONS
assert client.has_operation("listInferenceServices")

print("services python SDK alpha smoke ok")
