#!/usr/bin/env python3
"""Generate lightweight SDK Alpha artifacts from Core and Services OpenAPI specs."""

from __future__ import annotations

from pathlib import Path
import json
import re
import shutil
from typing import Any

import yaml


LAYERS = {
    "core": {
        "spec": "api/openapi/v1.yaml",
        "go_module": "github.com/kubercloud/ani-sdks/core-go",
        "py_package": "kubercloud_ani_core",
        "java_package": "com.kubercloud.ani.core",
        "ts_name": "@kubercloud/ani-core-alpha",
    },
    "services": {
        "spec": "api/openapi/services/v1.yaml",
        "go_module": "github.com/kubercloud/ani-sdks/services-go",
        "py_package": "kubercloud_ani_services",
        "java_package": "com.kubercloud.ani.services",
        "ts_name": "@kubercloud/ani-services-alpha",
    },
}

HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def load_spec(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def collect_metadata(spec: dict[str, Any], layer: str) -> dict[str, Any]:
    operations: list[dict[str, str]] = []
    for path, path_item in sorted(spec.get("paths", {}).items()):
        if not isinstance(path_item, dict):
            continue
        for method, operation in sorted(path_item.items()):
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            operations.append(
                {
                    "operationId": operation.get("operationId") or operation_id(method, path),
                    "method": method.upper(),
                    "path": path,
                    "scope": operation.get("x-ani-rbac-scope", ""),
                }
            )
    schemas = sorted(spec.get("components", {}).get("schemas", {}).keys())
    server_url = ""
    servers = spec.get("servers") or []
    if servers:
        server_url = servers[0].get("url", "")
    return {
        "layer": layer,
        "title": spec.get("info", {}).get("title", ""),
        "version": spec.get("info", {}).get("version", ""),
        "serverURL": server_url,
        "operations": operations,
        "schemas": schemas,
    }


def operation_id(method: str, path: str) -> str:
    tokens = re.sub(r"[^a-zA-Z0-9]+", " ", path).title().replace(" ", "")
    return method.lower() + tokens


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generated_header(comment: str) -> str:
    return f"{comment} Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.\n"


def go_string_list(values: list[str]) -> str:
    if not values:
        return ""
    return "\n\t" + ",\n\t".join(json.dumps(value) for value in values) + ",\n"


def generate_go(root: Path, layer: str, config: dict[str, str], metadata: dict[str, Any]) -> None:
    target = root / "sdks" / layer / "go"
    package_name = "anisdk"
    operations = [item["operationId"] for item in metadata["operations"]]
    paths = [f"{item['method']} {item['path']}" for item in metadata["operations"]]
    schemas = metadata["schemas"]
    write(
        target / "go.mod",
        f"module {config['go_module']}\n\ngo 1.22\n",
    )
    write(
        target / package_name / "client.go",
        generated_header("//")
        + f"""package {package_name}

const Layer = {json.dumps(layer)}
const Title = {json.dumps(metadata["title"])}
const Version = {json.dumps(metadata["version"])}
const ServerURL = {json.dumps(metadata["serverURL"])}

var Operations = []string{{{go_string_list(operations)}}}
var Paths = []string{{{go_string_list(paths)}}}
var Schemas = []string{{{go_string_list(schemas)}}}

type Client struct {{
\tBaseURL string
\tToken   string
}}

func NewClient(baseURL string, token string) Client {{
\tif baseURL == "" {{
\t\tbaseURL = ServerURL
\t}}
\treturn Client{{BaseURL: baseURL, Token: token}}
}}

func HasOperation(operationID string) bool {{
\tfor _, operation := range Operations {{
\t\tif operation == operationID {{
\t\t\treturn true
\t\t}}
\t}}
\treturn false
}}
""",
    )
    operation_check = ""
    if operations:
        operation_check = f"""\tif len(Operations) == 0 {{
\t\tt.Fatalf("expected generated operations")
\t}}
\tif !HasOperation({json.dumps(operations[0])}) {{
\t\tt.Fatalf("missing expected operation")
\t}}
"""
    write(
        target / package_name / "client_test.go",
        generated_header("//")
        + f"""package {package_name}

import "testing"

func TestSDKAlphaSmoke(t *testing.T) {{
\tclient := NewClient("", "token")
\tif client.BaseURL == "" || Title == "" || Version == "" {{
\t\tt.Fatalf("invalid SDK metadata")
\t}}
\tif len(Schemas) == 0 {{
\t\tt.Fatalf("expected generated schemas")
\t}}
{operation_check}
}}
""",
    )


def py_list(values: list[str]) -> str:
    return json.dumps(values, indent=4)


def generate_python(root: Path, layer: str, config: dict[str, str], metadata: dict[str, Any]) -> None:
    target = root / "sdks" / layer / "python"
    package = config["py_package"]
    operations = [item["operationId"] for item in metadata["operations"]]
    paths = [f"{item['method']} {item['path']}" for item in metadata["operations"]]
    write(
        target / package / "__init__.py",
        generated_header("#")
        + """from .client import Client, LAYER, TITLE, VERSION, SERVER_URL, OPERATIONS, PATHS, SCHEMAS

__all__ = [
    "Client",
    "LAYER",
    "TITLE",
    "VERSION",
    "SERVER_URL",
    "OPERATIONS",
    "PATHS",
    "SCHEMAS",
]
""",
    )
    write(
        target / package / "client.py",
        generated_header("#")
        + f'''LAYER = {json.dumps(layer)}
TITLE = {json.dumps(metadata["title"])}
VERSION = {json.dumps(metadata["version"])}
SERVER_URL = {json.dumps(metadata["serverURL"])}
OPERATIONS = {py_list(operations)}
PATHS = {py_list(paths)}
SCHEMAS = {py_list(metadata["schemas"])}


class Client:
    def __init__(self, base_url: str | None = None, token: str | None = None):
        self.base_url = base_url or SERVER_URL
        self.token = token

    def has_operation(self, operation_id: str) -> bool:
        return operation_id in OPERATIONS
''',
    )
    operation_check = ""
    if operations:
        operation_check = f"assert sdk.OPERATIONS\nassert client.has_operation({json.dumps(operations[0])})\n"
    write(
        target / "smoke.py",
        generated_header("#")
        + f"""import {package} as sdk

client = sdk.Client(token="token")
assert client.base_url
assert sdk.TITLE
assert sdk.VERSION
assert sdk.SCHEMAS
{operation_check}
print("{layer} python SDK alpha smoke ok")
""",
    )


def ts_array(values: list[str]) -> str:
    return json.dumps(values, indent=2)


def generate_typescript(root: Path, layer: str, config: dict[str, str], metadata: dict[str, Any]) -> None:
    target = root / "sdks" / layer / "typescript"
    operations = [item["operationId"] for item in metadata["operations"]]
    paths = [f"{item['method']} {item['path']}" for item in metadata["operations"]]
    package_json = {
        "name": config["ts_name"],
        "version": "1.0.0-alpha.0",
        "type": "module",
        "private": True,
        "exports": {"import": "./src/index.mjs", "types": "./src/index.ts"},
    }
    write(target / "package.json", json.dumps(package_json, indent=2) + "\n")
    ts_content = generated_header("//") + f"""export const layer = {json.dumps(layer)} as const;
export const title = {json.dumps(metadata["title"])} as const;
export const version = {json.dumps(metadata["version"])} as const;
export const serverURL = {json.dumps(metadata["serverURL"])} as const;
export const operations = {ts_array(operations)} as const;
export const paths = {ts_array(paths)} as const;
export const schemas = {ts_array(metadata["schemas"])} as const;

export interface ClientOptions {{
  baseURL?: string;
  token?: string;
}}

export class Client {{
  readonly baseURL: string;
  readonly token?: string;

  constructor(options: ClientOptions = {{}}) {{
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }}

  hasOperation(operationID: string): boolean {{
    return operations.includes(operationID as typeof operations[number]);
  }}
}}
"""
    write(target / "src" / "index.ts", ts_content)
    js_content = generated_header("//") + f"""export const layer = {json.dumps(layer)};
export const title = {json.dumps(metadata["title"])};
export const version = {json.dumps(metadata["version"])};
export const serverURL = {json.dumps(metadata["serverURL"])};
export const operations = {json.dumps(operations, indent=2)};
export const paths = {json.dumps(paths, indent=2)};
export const schemas = {json.dumps(metadata["schemas"], indent=2)};

export class Client {{
  constructor(options = {{}}) {{
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }}

  hasOperation(operationID) {{
    return operations.includes(operationID);
  }}
}}
"""
    write(target / "src" / "index.mjs", js_content)
    operation_check = ""
    if operations:
        operation_check = f"""if (operations.length === 0) {{
  throw new Error("expected generated operations");
}}
if (!client.hasOperation({json.dumps(operations[0])})) {{
  throw new Error("missing expected operation");
}}
"""
    write(
        target / "smoke.mjs",
        generated_header("//")
        + f"""import {{ Client, operations, schemas, title, version }} from "./src/index.mjs";

const client = new Client({{ token: "token" }});
if (!client.baseURL || !title || !version || schemas.length === 0) {{
  throw new Error("invalid SDK metadata");
}}
{operation_check}
console.log("{layer} typescript SDK alpha smoke ok");
""",
    )


def java_string_array(values: list[str]) -> str:
    if not values:
        return ""
    return "\n        " + ",\n        ".join(json.dumps(value) for value in values) + "\n    "


def generate_java(root: Path, layer: str, config: dict[str, str], metadata: dict[str, Any]) -> None:
    target = root / "sdks" / layer / "java"
    package = config["java_package"]
    package_path = Path(*package.split("."))
    operations = [item["operationId"] for item in metadata["operations"]]
    paths = [f"{item['method']} {item['path']}" for item in metadata["operations"]]
    write(
        target / "src/main/java" / package_path / "ApiClient.java",
        generated_header("//")
        + f"""package {package};

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public final class ApiClient {{
    public static final String LAYER = {json.dumps(layer)};
    public static final String TITLE = {json.dumps(metadata["title"])};
    public static final String VERSION = {json.dumps(metadata["version"])};
    public static final String SERVER_URL = {json.dumps(metadata["serverURL"])};
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList({java_string_array(operations)}));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList({java_string_array(paths)}));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList({java_string_array(metadata["schemas"])}));

    private final String baseUrl;
    private final String token;

    public ApiClient(String baseUrl, String token) {{
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }}

    public String baseUrl() {{
        return baseUrl;
    }}

    public String token() {{
        return token;
    }}

    public boolean hasOperation(String operationId) {{
        return OPERATIONS.contains(operationId);
    }}
}}
""",
    )
    operation_check = ""
    if operations:
        operation_check = f"""        if (ApiClient.OPERATIONS.isEmpty()) {{
            throw new IllegalStateException("expected generated operations");
        }}
        if (!client.hasOperation({json.dumps(operations[0])})) {{
            throw new IllegalStateException("missing expected operation");
        }}
"""
    write(
        target / "src/test/java" / package_path / "Smoke.java",
        generated_header("//")
        + f"""package {package};

public final class Smoke {{
    public static void main(String[] args) {{
        ApiClient client = new ApiClient("", "token");
        if (client.baseUrl().isEmpty() || ApiClient.TITLE.isEmpty() || ApiClient.VERSION.isEmpty()) {{
            throw new IllegalStateException("invalid SDK metadata");
        }}
        if (ApiClient.SCHEMAS.isEmpty()) {{
            throw new IllegalStateException("expected generated schemas");
        }}
{operation_check}
        System.out.println("{layer} java SDK alpha smoke ok");
    }}
}}
""",
    )


def generate_layer(root: Path, layer: str, config: dict[str, str]) -> None:
    metadata = collect_metadata(load_spec(root / config["spec"]), layer)
    layer_root = root / "sdks" / layer
    if layer_root.exists():
        shutil.rmtree(layer_root)
    write(layer_root / "sdk-metadata.json", json.dumps(metadata, indent=2) + "\n")
    generate_go(root, layer, config, metadata)
    generate_python(root, layer, config, metadata)
    generate_typescript(root, layer, config, metadata)
    generate_java(root, layer, config, metadata)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    for layer, config in LAYERS.items():
        generate_layer(root, layer, config)
    print("SDK Alpha artifacts generated")


if __name__ == "__main__":
    main()
