# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
LAYER = "services"
TITLE = "KuberCloud ANI Services API"
VERSION = "1.0.0"
SERVER_URL = "https://{host}/api/v1/svc"
OPERATIONS = [
    "listInferenceServices",
    "createInferenceService",
    "deleteInferenceService",
    "getInferenceService",
    "listKnowledgeBases",
    "createKnowledgeBase",
    "deleteKnowledgeBase",
    "getKnowledgeBase",
    "listKnowledgeBaseDocuments",
    "uploadKnowledgeBaseDocument",
    "deleteKnowledgeBaseDocument",
    "queryKnowledgeBase",
    "streamQueryKnowledgeBase",
    "listModels",
    "createModel",
    "importModel",
    "deleteModel",
    "getModel",
    "createModelVersion"
]
PATHS = [
    "GET /inference-services",
    "POST /inference-services",
    "DELETE /inference-services/{service_id}",
    "GET /inference-services/{service_id}",
    "GET /knowledge-bases",
    "POST /knowledge-bases",
    "DELETE /knowledge-bases/{kb_id}",
    "GET /knowledge-bases/{kb_id}",
    "GET /knowledge-bases/{kb_id}/documents",
    "POST /knowledge-bases/{kb_id}/documents",
    "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
    "POST /knowledge-bases/{kb_id}/query",
    "GET /knowledge-bases/{kb_id}/query/stream",
    "GET /models",
    "POST /models",
    "POST /models/import",
    "DELETE /models/{model_id}",
    "GET /models/{model_id}",
    "POST /models/{model_id}/versions"
]
SCHEMAS = [
    "AsyncTask",
    "CreateInferenceEndpointRequest",
    "CreateModelRequest",
    "CursorPage",
    "ErrorResponse",
    "InferenceEndpoint",
    "InferenceService",
    "KBDocument",
    "KBQueryRequest",
    "KBQueryResponse",
    "KnowledgeBase",
    "Model",
    "ModelVersion"
]


class Client:
    def __init__(self, base_url: str | None = None, token: str | None = None):
        self.base_url = base_url or SERVER_URL
        self.token = token

    def has_operation(self, operation_id: str) -> bool:
        return operation_id in OPERATIONS
