// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import { Client, operations, schemas, title, version } from "./src/index.mjs";

const client = new Client({ token: "token" });
if (!client.baseURL || !title || !version || schemas.length === 0) {
  throw new Error("invalid SDK metadata");
}
if (operations.length === 0) {
  throw new Error("expected generated operations");
}
if (!client.hasOperation("listInferenceServices")) {
  throw new Error("missing expected operation");
}

console.log("services typescript SDK alpha smoke ok");
