package runtime

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/kubercloud/ani/pkg/ports"
)

type LocalInstanceObservabilityService struct {
	now             func() time.Time
	mu              sync.RWMutex
	sessions        map[string]ports.InstanceExecSessionRecord
	consoleSessions map[string]ports.InstanceConsoleSessionRecord
}

type InstanceObservabilityOption func(*LocalInstanceObservabilityService)

func WithInstanceObservabilityClock(now func() time.Time) InstanceObservabilityOption {
	return func(service *LocalInstanceObservabilityService) {
		if now != nil {
			service.now = now
		}
	}
}

func NewLocalInstanceObservabilityService(options ...InstanceObservabilityOption) *LocalInstanceObservabilityService {
	service := &LocalInstanceObservabilityService{
		now:             time.Now,
		sessions:        make(map[string]ports.InstanceExecSessionRecord),
		consoleSessions: make(map[string]ports.InstanceConsoleSessionRecord),
	}
	for _, option := range options {
		option(service)
	}
	return service
}

func (s *LocalInstanceObservabilityService) ListLogs(_ context.Context, request ports.InstanceObservationListRequest) (ports.InstanceLogListResult, error) {
	if err := validateInstanceObservationIdentity(request.TenantID, request.InstanceID); err != nil {
		return ports.InstanceLogListResult{}, err
	}
	now := s.now().UTC()
	items := []ports.InstanceLogEntry{
		{Timestamp: now.Add(-2 * time.Minute), Level: "info", Message: "local profile instance runtime is running", Container: "main", Stream: "stdout"},
		{Timestamp: now.Add(-90 * time.Second), Level: "warn", Message: "local profile does not attach to a real provider log stream", Container: "main", Stream: "stderr"},
		{Timestamp: now.Add(-30 * time.Second), Level: "debug", Message: "dev_profile observation generated by local adapter", Container: "sidecar", Stream: "stdout"},
	}
	items = filterLogs(items, request.Level)
	items = limitLogEntries(items, normalizeLimit(request.Limit, 100, 1000))
	return ports.InstanceLogListResult{Items: items, Total: len(items), DevProfile: instanceObservabilityDevProfile()}, nil
}

func (s *LocalInstanceObservabilityService) ListEvents(_ context.Context, request ports.InstanceObservationListRequest) (ports.InstanceEventListResult, error) {
	if err := validateInstanceObservationIdentity(request.TenantID, request.InstanceID); err != nil {
		return ports.InstanceEventListResult{}, err
	}
	now := s.now().UTC()
	items := []ports.InstanceEventRecord{
		{ID: "evt-" + uuid.NewString(), InstanceID: request.InstanceID, Type: "Normal", Reason: "Scheduled", Message: "instance accepted by local profile scheduler", Count: 1, OccurredAt: now.Add(-3 * time.Minute)},
		{ID: "evt-" + uuid.NewString(), InstanceID: request.InstanceID, Type: "Warning", Reason: "LocalProfileOnly", Message: "provider runtime readiness is gated by live validation", Count: 1, OccurredAt: now.Add(-1 * time.Minute)},
	}
	items = filterEvents(items, request.Type)
	items = limitEventRecords(items, normalizeLimit(request.Limit, 50, 500))
	return ports.InstanceEventListResult{Items: items, Total: len(items), DevProfile: instanceObservabilityDevProfile()}, nil
}

func (s *LocalInstanceObservabilityService) GetMetrics(_ context.Context, request ports.InstanceObservationGetRequest) (ports.InstanceMetricsRecord, error) {
	if err := validateInstanceObservationIdentity(request.TenantID, request.InstanceID); err != nil {
		return ports.InstanceMetricsRecord{}, err
	}
	cpu := 18.5
	memUsed := 1536.0
	memTotal := 4096.0
	gpuUtil := 0.0
	gpuMemUsed := 0.0
	gpuMemTotal := 0.0
	rx := int64(1048576)
	tx := int64(524288)
	return ports.InstanceMetricsRecord{
		InstanceID:        request.InstanceID,
		Timestamp:         s.now().UTC(),
		CPUUtilizationPct: &cpu,
		MemoryUsedMB:      &memUsed,
		MemoryTotalMB:     &memTotal,
		GPUUtilizationPct: &gpuUtil,
		GPUMemoryUsedMB:   &gpuMemUsed,
		GPUMemoryTotalMB:  &gpuMemTotal,
		NetworkRXBytes:    &rx,
		NetworkTXBytes:    &tx,
		DevProfile:        instanceObservabilityDevProfile(),
	}, nil
}

func (s *LocalInstanceObservabilityService) ListSecurityEvents(_ context.Context, request ports.InstanceObservationListRequest) (ports.InstanceSecurityEventListResult, error) {
	if err := validateInstanceObservationIdentity(request.TenantID, request.InstanceID); err != nil {
		return ports.InstanceSecurityEventListResult{}, err
	}
	now := s.now().UTC()
	items := []ports.InstanceSecurityEventRecord{
		{ID: uuid.NewString(), InstanceID: request.InstanceID, EventType: "sandbox_egress_policy", Severity: "info", Description: "deny_all egress policy recorded by local profile", OccurredAt: now.Add(-2 * time.Minute)},
		{ID: uuid.NewString(), InstanceID: request.InstanceID, EventType: "runtime_provider_gate", Severity: "warning", Description: "real sandbox runtime provider is gated separately", OccurredAt: now.Add(-1 * time.Minute)},
	}
	items = filterSecurityEvents(items, request.Severity)
	items = limitSecurityEventRecords(items, normalizeLimit(request.Limit, 50, 500))
	return ports.InstanceSecurityEventListResult{Items: items, Total: len(items), DevProfile: instanceObservabilityDevProfile()}, nil
}

func (s *LocalInstanceObservabilityService) CreateExecSession(_ context.Context, request ports.InstanceExecSessionCreateRequest) (ports.InstanceExecSessionRecord, error) {
	if err := validateInstanceObservationIdentity(request.TenantID, request.InstanceID); err != nil {
		return ports.InstanceExecSessionRecord{}, err
	}
	if strings.TrimSpace(request.IdempotencyKey) == "" {
		return ports.InstanceExecSessionRecord{}, fmt.Errorf("%w: idempotency_key is required", ports.ErrInvalid)
	}
	key := request.TenantID + "/" + request.InstanceID + "/" + request.IdempotencyKey
	s.mu.RLock()
	if record, ok := s.sessions[key]; ok {
		s.mu.RUnlock()
		return record, nil
	}
	s.mu.RUnlock()

	now := s.now().UTC()
	sessionID := uuid.NewString()
	record := ports.InstanceExecSessionRecord{
		ID:         sessionID,
		InstanceID: request.InstanceID,
		WSURL:      "ws://127.0.0.1:8080/api/v1/instances/" + request.InstanceID + "/exec/" + sessionID,
		ExpiresAt:  now.Add(15 * time.Minute),
		DevProfile: instanceObservabilityDevProfile(),
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if existing, ok := s.sessions[key]; ok {
		return existing, nil
	}
	s.sessions[key] = record
	return record, nil
}

// CreateConsoleSession 为 VM 实例创建本地 console 会话记录，支持幂等。
func (s *LocalInstanceObservabilityService) CreateConsoleSession(_ context.Context, request ports.InstanceConsoleSessionCreateRequest) (ports.InstanceConsoleSessionRecord, error) {
	if err := validateInstanceObservationIdentity(request.TenantID, request.InstanceID); err != nil {
		return ports.InstanceConsoleSessionRecord{}, err
	}
	protocol := normalizeConsoleProtocol(request.Protocol)
	key := request.TenantID + "/" + request.InstanceID + "/" + protocol
	if strings.TrimSpace(request.IdempotencyKey) != "" {
		key = request.TenantID + "/" + request.InstanceID + "/" + request.IdempotencyKey
	}
	s.mu.RLock()
	if record, ok := s.consoleSessions[key]; ok {
		s.mu.RUnlock()
		return record, nil
	}
	s.mu.RUnlock()

	now := s.now().UTC()
	sessionID := uuid.NewString()
	record := ports.InstanceConsoleSessionRecord{
		SessionID:  sessionID,
		InstanceID: request.InstanceID,
		Protocol:   protocol,
		ConnectURL: "ws://127.0.0.1:8080/api/v1/instances/" + request.InstanceID + "/console/" + sessionID,
		URL:        "ws://127.0.0.1:8080/api/v1/instances/" + request.InstanceID + "/console/" + sessionID,
		ExpiresAt:  now.Add(15 * time.Minute),
		DevProfile: instanceObservabilityDevProfile(),
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if existing, ok := s.consoleSessions[key]; ok {
		return existing, nil
	}
	s.consoleSessions[key] = record
	return record, nil
}

func validateInstanceObservationIdentity(tenantID string, instanceID string) error {
	if strings.TrimSpace(tenantID) == "" {
		return fmt.Errorf("%w: tenant_id is required", ports.ErrInvalid)
	}
	if strings.TrimSpace(instanceID) == "" {
		return fmt.Errorf("%w: instance_id is required", ports.ErrInvalid)
	}
	return nil
}

func normalizeConsoleProtocol(protocol string) string {
	protocol = strings.ToLower(strings.TrimSpace(protocol))
	if protocol == "" {
		return "vnc"
	}
	return protocol
}

func instanceObservabilityDevProfile() ports.DevProfileInfo {
	return ports.DevProfileInfo{
		Mode:         "local",
		Provider:     "local-instance-observability",
		RealProvider: false,
		Reason:       "Core dev/local profile emits synthetic observation data; real provider readiness is gated separately",
	}
}

func normalizeLimit(value int, fallback int, max int) int {
	if value <= 0 {
		return fallback
	}
	if value > max {
		return max
	}
	return value
}

func filterLogs(items []ports.InstanceLogEntry, level string) []ports.InstanceLogEntry {
	level = strings.TrimSpace(level)
	if level == "" {
		return items
	}
	filtered := make([]ports.InstanceLogEntry, 0, len(items))
	for _, item := range items {
		if item.Level == level {
			filtered = append(filtered, item)
		}
	}
	return filtered
}

func filterEvents(items []ports.InstanceEventRecord, eventType string) []ports.InstanceEventRecord {
	eventType = strings.TrimSpace(eventType)
	if eventType == "" {
		return items
	}
	filtered := make([]ports.InstanceEventRecord, 0, len(items))
	for _, item := range items {
		if item.Type == eventType {
			filtered = append(filtered, item)
		}
	}
	return filtered
}

func filterSecurityEvents(items []ports.InstanceSecurityEventRecord, severity string) []ports.InstanceSecurityEventRecord {
	severity = strings.TrimSpace(severity)
	if severity == "" {
		return items
	}
	filtered := make([]ports.InstanceSecurityEventRecord, 0, len(items))
	for _, item := range items {
		if item.Severity == severity {
			filtered = append(filtered, item)
		}
	}
	return filtered
}

func limitLogEntries(items []ports.InstanceLogEntry, limit int) []ports.InstanceLogEntry {
	if len(items) > limit {
		return items[:limit]
	}
	return items
}

func limitEventRecords(items []ports.InstanceEventRecord, limit int) []ports.InstanceEventRecord {
	if len(items) > limit {
		return items[:limit]
	}
	return items
}

func limitSecurityEventRecords(items []ports.InstanceSecurityEventRecord, limit int) []ports.InstanceSecurityEventRecord {
	if len(items) > limit {
		return items[:limit]
	}
	return items
}

var _ ports.InstanceObservability = (*LocalInstanceObservabilityService)(nil)
