// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

const Layer = "services"
const Title = "KuberCloud ANI Services API"
const Version = "1.0.0"
const ServerURL = "https://{host}/api/v1/svc"

var Operations = []string{
	"listInferenceServices",
	"createInferenceService",
	"deleteInferenceService",
	"getInferenceService",
	"listKnowledgeBases",
	"createKnowledgeBase",
	"deleteKnowledgeBase",
	"getKnowledgeBase",
	"listKnowledgeBaseDocuments",
	"uploadKnowledgeBaseDocument",
	"deleteKnowledgeBaseDocument",
	"queryKnowledgeBase",
	"streamQueryKnowledgeBase",
	"listModels",
	"createModel",
	"importModel",
	"deleteModel",
	"getModel",
	"createModelVersion",
}
var Paths = []string{
	"GET /inference-services",
	"POST /inference-services",
	"DELETE /inference-services/{service_id}",
	"GET /inference-services/{service_id}",
	"GET /knowledge-bases",
	"POST /knowledge-bases",
	"DELETE /knowledge-bases/{kb_id}",
	"GET /knowledge-bases/{kb_id}",
	"GET /knowledge-bases/{kb_id}/documents",
	"POST /knowledge-bases/{kb_id}/documents",
	"DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
	"POST /knowledge-bases/{kb_id}/query",
	"GET /knowledge-bases/{kb_id}/query/stream",
	"GET /models",
	"POST /models",
	"POST /models/import",
	"DELETE /models/{model_id}",
	"GET /models/{model_id}",
	"POST /models/{model_id}/versions",
}
var Schemas = []string{
	"AsyncTask",
	"CreateInferenceEndpointRequest",
	"CreateModelRequest",
	"CursorPage",
	"ErrorResponse",
	"InferenceEndpoint",
	"InferenceService",
	"KBDocument",
	"KBQueryRequest",
	"KBQueryResponse",
	"KnowledgeBase",
	"Model",
	"ModelVersion",
}

type Client struct {
	BaseURL string
	Token   string
}

func NewClient(baseURL string, token string) Client {
	if baseURL == "" {
		baseURL = ServerURL
	}
	return Client{BaseURL: baseURL, Token: token}
}

func HasOperation(operationID string) bool {
	for _, operation := range Operations {
		if operation == operationID {
			return true
		}
	}
	return false
}
