/**
 * ANI Services API client — types generated from OpenAPI Spec.
 *
 * DO NOT hand-write fetch calls. Use this client so all requests are type-safe
 * and reflect Spec changes when `make gen-console-api` is run.
 *
 * Usage:
 *   import { api } from '@/api/client'
 *   const { data, error } = await api.GET('/models')
 */
import createClient from 'openapi-fetch'
// schema.d.ts is generated by:
//   npx openapi-typescript api/openapi/services/v1.yaml -o frontends/console/src/api/schema.d.ts
// If this import fails, run: make gen-console-api
import type { paths } from './schema'

export const api = createClient<paths>({
  baseUrl: '/api/v1/svc',
  headers: {
    'Content-Type': 'application/json',
  },
})

export { setAuthToken } from './auth'
