/**
 * ANI Core API client — types generated from Core OpenAPI Spec.
 *
 * Use for infrastructure APIs: instances, metering, tasks, registry, auth, etc.
 * Business APIs (models, knowledge-bases) use `@/api/client` instead.
 *
 * Usage:
 *   import { coreApi } from '@/api/coreClient'
 *   const { data } = await coreApi.GET('/metering/usage', { params: { query: { ... } } })
 */
import createClient from 'openapi-fetch'
// core-schema.d.ts is generated by:
//   npx openapi-typescript api/openapi/v1.yaml -o frontends/console/src/api/core-schema.d.ts
// If this import fails, run: make gen-console-api
import type { paths } from './core-schema'

export const coreApi = createClient<paths>({
  baseUrl: '/api/v1',
  headers: {
    'Content-Type': 'application/json',
  },
})

export { setAuthToken } from './auth'
