/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取模型列表 */
        get: operations["listModels"];
        put?: never;
        /** 创建模型元数据记录 */
        post: operations["createModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从 HuggingFace 或 ModelScope 异步导入模型 */
        post: operations["importModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取模型详情 */
        get: operations["getModel"];
        put?: never;
        post?: never;
        /** 删除模型 */
        delete: operations["deleteModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传模型版本 */
        post: operations["createModelVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取推理服务列表 */
        get: operations["listInferenceServices"];
        put?: never;
        /** 部署推理服务 */
        post: operations["createInferenceService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference-services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取推理服务详情 */
        get: operations["getInferenceService"];
        put?: never;
        post?: never;
        /** 停止并删除推理服务 */
        delete: operations["deleteInferenceService"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference-services/{service_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取推理服务日志 */
        get: operations["getInferenceServiceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference-services/{service_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 推理服务调用测试 */
        post: operations["testInferenceService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inference-services/{service_id}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新推理服务限流与访问策略 */
        put: operations["updateInferenceServicePolicies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识库列表 */
        get: operations["listKnowledgeBases"];
        put?: never;
        /** 创建知识库 */
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取知识库详情 */
        get: operations["getKnowledgeBase"];
        put?: never;
        post?: never;
        /** 删除知识库 */
        delete: operations["deleteKnowledgeBase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文档列表 */
        get: operations["listKnowledgeBaseDocuments"];
        put?: never;
        /** 上传文档 */
        post: operations["uploadKnowledgeBaseDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除知识库文档 */
        delete: operations["deleteKnowledgeBaseDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 知识库问答 */
        post: operations["queryKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识库问答 SSE 流式 */
        get: operations["streamQueryKnowledgeBase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识库引用来源列表 */
        get: operations["listKnowledgeBaseCitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识库对话历史列表 */
        get: operations["listKnowledgeBaseSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新知识库访问权限 */
        put: operations["updateKnowledgeBasePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpu-containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GPU容器列表（已废弃，请使用 /api/v1/instances?kind=gpu_container）
         * @deprecated
         */
        get: operations["listGpuContainers"];
        put?: never;
        /**
         * 创建GPU容器（已废弃，请使用 POST /api/v1/instances）
         * @deprecated
         */
        post: operations["createGpuContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpu-containers/available-gpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询可用GPU资源（已废弃，请使用 GET /api/v1/gpu-inventory）
         * @deprecated
         */
        get: operations["listAvailableGpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpu-containers/{container_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取GPU容器详情（已废弃）
         * @deprecated
         */
        get: operations["getGpuContainer"];
        put?: never;
        post?: never;
        /**
         * 删除GPU容器（已废弃）
         * @deprecated
         */
        delete: operations["deleteGpuContainer"];
        options?: never;
        head?: never;
        /**
         * 更新GPU容器配置（已废弃）
         * @deprecated
         */
        patch: operations["patchGpuContainer"];
        trace?: never;
    };
    "/gpu-containers/{container_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取GPU容器监控指标（已废弃）
         * @deprecated
         */
        get: operations["getGpuContainerMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpu-containers/{container_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GPU容器版本历史（已废弃）
         * @deprecated
         */
        get: operations["listGpuContainerVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpu-containers/{container_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 回滚GPU容器到指定版本（已废弃）
         * @deprecated
         */
        post: operations["rollbackGpuContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gpu-containers/{container_id}/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重建GPU容器（已废弃）
         * @deprecated
         */
        post: operations["rebuildGpuContainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sandbox列表（已废弃，请使用 /api/v1/instances?kind=sandbox）
         * @deprecated
         */
        get: operations["listSandboxes"];
        put?: never;
        /**
         * 创建Sandbox（已废弃，请使用 POST /api/v1/instances）
         * @deprecated
         */
        post: operations["createSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandbox_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取Sandbox详情（已废弃）
         * @deprecated
         */
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        /**
         * 删除Sandbox（已废弃）
         * @deprecated
         */
        delete: operations["deleteSandbox"];
        options?: never;
        head?: never;
        /**
         * 更新Sandbox配置（已废弃）
         * @deprecated
         */
        patch: operations["patchSandbox"];
        trace?: never;
    };
    "/sandboxes/{sandbox_id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 延期Sandbox有效期（已废弃）
         * @deprecated
         */
        post: operations["extendSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandbox_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 暂停Sandbox（已废弃）
         * @deprecated
         */
        post: operations["pauseSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandbox_id}/security-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sandbox安全事件列表（已废弃，请使用 GET /api/v1/instances/{id}/security-events）
         * @deprecated
         */
        get: operations["listSandboxSecurityEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{sandbox_id}/security-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sandbox安全概览（已废弃）
         * @deprecated
         */
        get: operations["getSandboxSecurityOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 租户成员列表 */
        get: operations["listTenantMembers"];
        put?: never;
        /** 邀请成员加入租户 */
        post: operations["inviteTenantMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取租户成员详情 */
        get: operations["getTenantMember"];
        put?: never;
        post?: never;
        /** 移除租户成员 */
        delete: operations["removeTenantMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色列表 */
        get: operations["listTenantRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新角色权限配置 */
        put: operations["updateTenantRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/sso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取SSO配置 */
        get: operations["getSsoConfig"];
        /** 更新SSO配置 */
        put: operations["updateSsoConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Webhook列表 */
        get: operations["listWebhooks"];
        put?: never;
        /** 创建Webhook */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除Webhook */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenant/webhooks/{webhook_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Webhook 投递日志 */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 第三方集成列表 */
        get: operations["listIntegrations"];
        put?: never;
        /** 创建第三方集成 */
        post: operations["createIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建企微/钉钉 Bot 集成 */
        post: operations["createIntegrationBot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            code: string;
            message: string;
            request_id: string;
            details?: {
                [key: string]: unknown;
            };
        };
        CursorPage: {
            next_cursor?: string | null;
        };
        AsyncTask: {
            /** Format: uuid */
            id: string;
            idempotency_key: string;
            task_type: string;
            resource_type?: string | null;
            /** Format: uuid */
            resource_id?: string | null;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "cancelled" | "dead_letter";
            attempt_count?: number;
            max_attempts?: number;
            progress_pct?: number;
            result?: Record<string, never> | null;
            error_message?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Model: {
            /** Format: uuid */
            id: string;
            name: string;
            display_name?: string;
            /** @enum {string} */
            source: "upload" | "huggingface" | "modelscope" | "builtin";
            capabilities?: string[];
            /** @enum {string} */
            status: "pending" | "downloading" | "ready" | "error" | "deleted";
            total_size_bytes?: number;
            /** Format: date-time */
            created_at: string;
        };
        ModelVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            model_id: string;
            version: string;
            /** @enum {string} */
            format: "safetensors" | "gguf" | "pytorch";
            is_encrypted?: boolean;
            size_bytes?: number;
            /** Format: date-time */
            created_at: string;
        };
        InferenceService: {
            /** Format: uuid */
            id: string;
            name: string;
            model: string;
            /** @default 1 */
            replicas: number;
            gpu_type?: string | null;
            /** @default 1 */
            gpu_count_per_pod: number;
            /** @default 8 */
            max_concurrency: number;
            /** @enum {string} */
            status: "pending" | "deploying" | "running" | "stopping" | "stopped" | "failed";
            endpoint_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateModelRequest: {
            /**
             * Format: uuid
             * @description 客户端生成UUID，防重复提交
             */
            idempotency_key: string;
            name: string;
            /** @enum {string} */
            source: "upload" | "huggingface" | "modelscope";
            source_url?: string;
        };
        InferenceEndpoint: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            model_version_id: string;
            /** @default 1 */
            replicas: number;
            gpu_profile?: string;
            /** @enum {string} */
            status: "pending" | "deploying" | "running" | "stopping" | "stopped" | "failed";
            endpoint_url?: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateInferenceEndpointRequest: {
            /** Format: uuid */
            idempotency_key: string;
            name: string;
            /** Format: uuid */
            model_version_id: string;
            /** @default 1 */
            replicas: number;
            gpu_profile?: string;
        };
        KnowledgeBase: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "active" | "rebuilding" | "deleted";
            doc_count?: number;
            /** Format: date-time */
            created_at: string;
        };
        KBDocument: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            knowledge_base_id: string;
            file_name: string;
            content_type?: string | null;
            size_bytes?: number;
            /** @enum {string} */
            status: "uploaded" | "parsing" | "indexed" | "failed" | "deleted";
            /** Format: date-time */
            created_at: string;
        };
        KBQueryRequest: {
            question: string;
            /** @default 5 */
            top_k: number;
            /** Format: uuid */
            session_id?: string | null;
        };
        KBQueryResponse: {
            answer: string;
            sources: {
                /** Format: uuid */
                doc_id?: string;
                file_name?: string;
                page?: number;
                content?: string;
                score?: number;
            }[];
            /** Format: uuid */
            session_id?: string;
            input_tokens?: number;
            output_tokens?: number;
        };
        GpuContainer: {
            /** Format: uuid */
            id: string;
            name: string;
            display_name?: string | null;
            image: string;
            gpu_type: string;
            gpu_count: number;
            cpu_cores?: number | null;
            memory_gb?: number | null;
            storage_gb?: number | null;
            /** @enum {string} */
            status: "pending" | "running" | "stopped" | "failed" | "deleted";
            endpoint_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        CreateGpuContainerRequest: {
            /**
             * Format: uuid
             * @description 客户端生成UUID，防重复提交
             */
            idempotency_key: string;
            name: string;
            display_name?: string;
            image: string;
            gpu_type: string;
            /** @default 1 */
            gpu_count: number;
            cpu_cores?: number;
            memory_gb?: number;
            storage_gb?: number;
            env?: {
                [key: string]: string;
            };
        };
        PatchGpuContainerRequest: {
            /** Format: uuid */
            idempotency_key: string;
            display_name?: string;
            replicas?: number;
            env?: {
                [key: string]: string;
            };
        };
        GpuContainerMetrics: {
            gpu_utilization_pct?: number;
            gpu_memory_used_mb?: number;
            gpu_memory_total_mb?: number;
            cpu_utilization_pct?: number;
            memory_used_mb?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        GpuContainerVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            container_id: string;
            image: string;
            is_current?: boolean;
            /** Format: date-time */
            created_at: string;
        };
        AvailableGpu: {
            gpu_type: string;
            available_count: number;
            total_count: number;
            node_name?: string | null;
        };
        Sandbox: {
            /** Format: uuid */
            id: string;
            name: string;
            image: string;
            /** @enum {string} */
            status: "pending" | "running" | "paused" | "expired" | "deleted";
            endpoint_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        CreateSandboxRequest: {
            /** Format: uuid */
            idempotency_key: string;
            name: string;
            image: string;
            /** @default 24 */
            ttl_hours: number;
            cpu_cores?: number;
            memory_gb?: number;
            env?: {
                [key: string]: string;
            };
        };
        PatchSandboxRequest: {
            /** Format: uuid */
            idempotency_key: string;
            env?: {
                [key: string]: string;
            };
        };
        ExtendSandboxRequest: {
            /** Format: uuid */
            idempotency_key: string;
            extend_hours: number;
        };
        SecurityEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sandbox_id: string;
            event_type: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            description?: string | null;
            /** Format: date-time */
            occurred_at: string;
        };
        SecurityOverview: {
            /** Format: uuid */
            sandbox_id: string;
            total_events: number;
            critical_count: number;
            warning_count: number;
            /** Format: date-time */
            last_event_at?: string | null;
        };
        TenantMember: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            name?: string | null;
            role: string;
            /** Format: date-time */
            joined_at: string;
        };
        InviteMemberRequest: {
            /** Format: uuid */
            idempotency_key: string;
            /** Format: email */
            email: string;
            role: string;
        };
        TenantRole: {
            id: string;
            name: string;
            description?: string | null;
            permissions: string[];
        };
        SsoConfig: {
            enabled?: boolean;
            /** @enum {string|null} */
            provider?: "oidc" | "saml" | null;
            /** Format: uri */
            issuer_url?: string | null;
            client_id?: string | null;
            /** Format: uri */
            redirect_url?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        UpdateSsoConfigRequest: {
            /** Format: uuid */
            idempotency_key: string;
            enabled?: boolean;
            /** @enum {string} */
            provider?: "oidc" | "saml";
            /** Format: uri */
            issuer_url?: string;
            client_id?: string;
            client_secret?: string;
            /** Format: uri */
            redirect_url?: string;
        };
        Webhook: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            events: string[];
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateWebhookRequest: {
            /** Format: uuid */
            idempotency_key: string;
            /** Format: uri */
            url: string;
            events: string[];
            secret?: string;
        };
        InferenceServiceLogEntry: {
            /** Format: date-time */
            timestamp: string;
            /** @enum {string} */
            level: "debug" | "info" | "warn" | "error";
            message: string;
            container?: string | null;
            /** @enum {string|null} */
            stream?: "stdout" | "stderr" | null;
        };
        InferenceServiceLogListResponse: {
            items: components["schemas"]["InferenceServiceLogEntry"][];
            next_cursor?: string | null;
        };
        InferenceTestRequest: {
            /** Format: uuid */
            idempotency_key: string;
            input: {
                [key: string]: unknown;
            };
            /** @default 30 */
            timeout_seconds: number;
        };
        InferenceTestResponse: {
            output: {
                [key: string]: unknown;
            };
            latency_ms: number;
            model_id?: string | null;
            /** @enum {string} */
            status: "success" | "timeout" | "error";
        };
        InferenceServicePolicies: {
            rate_limit_rpm?: number | null;
            max_concurrency?: number | null;
            allowed_tenant_ids?: string[] | null;
            /** @enum {string|null} */
            auth_mode?: "api_key" | "jwt" | "none" | null;
        };
        UpdateInferenceServicePoliciesRequest: {
            /** Format: uuid */
            idempotency_key: string;
            rate_limit_rpm?: number | null;
            max_concurrency?: number | null;
            allowed_tenant_ids?: string[];
            /** @enum {string} */
            auth_mode?: "api_key" | "jwt" | "none";
        };
        KBCitation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            kb_id: string;
            /** Format: uuid */
            doc_id: string;
            file_name: string;
            page?: number | null;
            content: string;
            score?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        KBCitationListResponse: {
            items: components["schemas"]["KBCitation"][];
            next_cursor?: string | null;
        };
        KBSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            kb_id: string;
            message_count?: number;
            last_query?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_active_at?: string | null;
        };
        KBSessionListResponse: {
            items: components["schemas"]["KBSession"][];
            next_cursor?: string | null;
        };
        UpdateKBPermissionsRequest: {
            /** Format: uuid */
            idempotency_key: string;
            public_read?: boolean;
            allowed_user_ids?: string[];
        };
        UpdateTenantRoleRequest: {
            /** Format: uuid */
            idempotency_key: string;
            name?: string;
            description?: string | null;
            permissions: string[];
        };
        WebhookDelivery: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            webhook_id: string;
            event_type: string;
            payload?: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            status: "pending" | "delivered" | "failed" | "retrying";
            http_status?: number | null;
            attempt_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at?: string | null;
        };
        WebhookDeliveryListResponse: {
            items: components["schemas"]["WebhookDelivery"][];
            next_cursor?: string | null;
        };
        Integration: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "dingtalk" | "wechat_work" | "lark" | "slack" | "email" | "generic_webhook";
            name: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: uri */
            webhook_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        IntegrationListResponse: {
            items: components["schemas"]["Integration"][];
            next_cursor?: string | null;
        };
        CreateIntegrationRequest: {
            /** Format: uuid */
            idempotency_key: string;
            /** @enum {string} */
            type: "dingtalk" | "wechat_work" | "lark" | "slack" | "email" | "generic_webhook";
            name: string;
            /** Format: uri */
            webhook_url?: string;
            config?: {
                [key: string]: unknown;
            };
        };
        IntegrationBot: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            integration_id: string;
            name: string;
            app_id: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            created_at: string;
        };
        CreateIntegrationBotRequest: {
            /** Format: uuid */
            idempotency_key: string;
            /** Format: uuid */
            integration_id: string;
            name: string;
            app_id: string;
            app_secret: string;
        };
    };
    responses: {
        /** @description 请求参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未认证 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 无权限 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 前置条件不满足（code=PRECONDITION_FAILED） */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModels: {
        parameters: {
            query?: {
                status?: "pending" | "downloading" | "ready" | "error" | "deleted";
                limit?: number;
                /** @description 上一页返回的 next_cursor */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        items?: components["schemas"]["Model"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description 客户端生成UUID，防重复提交
                     */
                    idempotency_key: string;
                    name: string;
                    display_name: string;
                    description?: string;
                    capabilities?: ("text-generation" | "embedding" | "speech-to-text")[];
                };
            };
        };
        responses: {
            /** @description 模型记录已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    importModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    source: "huggingface" | "modelscope";
                    repo_id: string;
                    /** @default main */
                    revision?: string;
                    idempotency_key: string;
                    /** Format: uri */
                    webhook_url?: string;
                };
            };
        };
        responses: {
            /** @description 导入任务已提交 */
            202: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createModelVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    idempotency_key: string;
                    version: string;
                    /** @enum {string} */
                    format: "safetensors" | "gguf" | "pytorch";
                    storage_path: string;
                    checksum_sha256: string;
                    size_bytes: number;
                    /** @default false */
                    is_encrypted?: boolean;
                };
            };
        };
        responses: {
            /** @description 模型版本已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersion"];
                };
            };
        };
    };
    listInferenceServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 推理服务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["InferenceService"][];
                    };
                };
            };
        };
    };
    createInferenceService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    idempotency_key: string;
                    name: string;
                    model: string;
                    /** @default 1 */
                    replicas?: number;
                    gpu_type?: string;
                    /** @default 1 */
                    gpu_count_per_pod?: number;
                    /** @default 8 */
                    max_concurrency?: number;
                };
            };
        };
        responses: {
            /** @description 推理服务部署已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceService"];
                };
            };
        };
    };
    getInferenceService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 推理服务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceService"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteInferenceService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 停止任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getInferenceServiceLogs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                level?: "debug" | "info" | "warn" | "error";
            };
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 日志列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceServiceLogListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    testInferenceService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InferenceTestRequest"];
            };
        };
        responses: {
            /** @description 测试推理结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceTestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateInferenceServicePolicies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInferenceServicePoliciesRequest"];
            };
        };
        responses: {
            /** @description 更新后的策略 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceServicePolicies"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["KnowledgeBase"][];
                    };
                };
            };
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    idempotency_key: string;
                    name: string;
                    description?: string;
                    /** @default bge-m3 */
                    embedding_model?: string;
                    /** @default 512 */
                    chunk_size?: number;
                    /** @default 5 */
                    top_k?: number;
                };
            };
        };
        responses: {
            /** @description 知识库已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
        };
    };
    getKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 知识库详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listKnowledgeBaseDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["KBDocument"][];
                    };
                };
            };
        };
    };
    uploadKnowledgeBaseDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 文档已上传，解析任务进行中 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KBDocument"];
                };
            };
        };
    };
    deleteKnowledgeBaseDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    queryKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                    /** Format: uuid */
                    session_id?: string | null;
                    idempotency_key: string;
                    /** @default 5 */
                    top_k?: number;
                    /**
                     * Format: float
                     * @default 0.3
                     */
                    score_threshold?: number;
                };
            };
        };
        responses: {
            /** @description JSON 格式的问答结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KBQueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamQueryKnowledgeBase: {
        parameters: {
            query: {
                question: string;
                session_id?: string;
            };
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listKnowledgeBaseCitations: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 引用来源列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KBCitationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listKnowledgeBaseSessions: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 对话历史列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KBSessionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateKnowledgeBasePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKBPermissionsRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGpuContainers: {
        parameters: {
            query?: {
                status?: "pending" | "running" | "stopped" | "failed" | "deleted";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPU容器列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        items?: components["schemas"]["GpuContainer"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createGpuContainer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGpuContainerRequest"];
            };
        };
        responses: {
            /** @description GPU容器创建任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuContainer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listAvailableGpus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可用GPU列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AvailableGpu"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGpuContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPU容器详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuContainer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteGpuContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchGpuContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchGpuContainerRequest"];
            };
        };
        responses: {
            /** @description 更新后的GPU容器 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuContainer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getGpuContainerMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前指标 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuContainerMetrics"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGpuContainerVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["GpuContainerVersion"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    rollbackGpuContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    idempotency_key: string;
                    /** Format: uuid */
                    version_id: string;
                };
            };
        };
        responses: {
            /** @description 回滚任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    rebuildGpuContainer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                container_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    idempotency_key: string;
                    image?: string;
                };
            };
        };
        responses: {
            /** @description 重建任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSandboxes: {
        parameters: {
            query?: {
                status?: "pending" | "running" | "paused" | "expired" | "deleted";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"] & {
                        items?: components["schemas"]["Sandbox"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSandboxRequest"];
            };
        };
        responses: {
            /** @description Sandbox创建任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSandboxRequest"];
            };
        };
        responses: {
            /** @description 更新后的Sandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    extendSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendSandboxRequest"];
            };
        };
        responses: {
            /** @description 延期后的Sandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    pauseSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    idempotency_key: string;
                };
            };
        };
        responses: {
            /** @description 暂停任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSandboxSecurityEvents: {
        parameters: {
            query?: {
                severity?: "info" | "warning" | "critical";
                limit?: number;
            };
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 安全事件列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["SecurityEvent"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSandboxSecurityOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandbox_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 安全概览 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityOverview"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTenantMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成员列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["TenantMember"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    inviteTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description 邀请已发送 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成员详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantMember"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenantRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["TenantRole"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateTenantRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantRoleRequest"];
            };
        };
        responses: {
            /** @description 更新后的角色 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantRole"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSsoConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSO配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSsoConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSsoConfigRequest"];
            };
        };
        responses: {
            /** @description 更新后的SSO配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Webhook"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["PreconditionFailed"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                status?: "pending" | "delivered" | "failed" | "retrying";
            };
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投递日志列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDeliveryListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 集成列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntegrationRequest"];
            };
        };
        responses: {
            /** @description 集成已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Integration"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    createIntegrationBot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntegrationBotRequest"];
            };
        };
        responses: {
            /** @description Bot 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationBot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
