// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.services;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public final class ApiClient {
    public static final String LAYER = "services";
    public static final String TITLE = "KuberCloud ANI Services API";
    public static final String VERSION = "1.0.0";
    public static final String SERVER_URL = "https://{host}/api/v1/svc";
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listInferenceServices",
        "createInferenceService",
        "deleteInferenceService",
        "getInferenceService",
        "listKnowledgeBases",
        "createKnowledgeBase",
        "deleteKnowledgeBase",
        "getKnowledgeBase",
        "listKnowledgeBaseDocuments",
        "uploadKnowledgeBaseDocument",
        "deleteKnowledgeBaseDocument",
        "queryKnowledgeBase",
        "streamQueryKnowledgeBase",
        "listModels",
        "createModel",
        "importModel",
        "deleteModel",
        "getModel",
        "createModelVersion"
    ));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList(
        "GET /inference-services",
        "POST /inference-services",
        "DELETE /inference-services/{service_id}",
        "GET /inference-services/{service_id}",
        "GET /knowledge-bases",
        "POST /knowledge-bases",
        "DELETE /knowledge-bases/{kb_id}",
        "GET /knowledge-bases/{kb_id}",
        "GET /knowledge-bases/{kb_id}/documents",
        "POST /knowledge-bases/{kb_id}/documents",
        "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
        "POST /knowledge-bases/{kb_id}/query",
        "GET /knowledge-bases/{kb_id}/query/stream",
        "GET /models",
        "POST /models",
        "POST /models/import",
        "DELETE /models/{model_id}",
        "GET /models/{model_id}",
        "POST /models/{model_id}/versions"
    ));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList(
        "AsyncTask",
        "CreateInferenceEndpointRequest",
        "CreateModelRequest",
        "CursorPage",
        "ErrorResponse",
        "InferenceEndpoint",
        "InferenceService",
        "KBDocument",
        "KBQueryRequest",
        "KBQueryResponse",
        "KnowledgeBase",
        "Model",
        "ModelVersion"
    ));

    private final String baseUrl;
    private final String token;

    public ApiClient(String baseUrl, String token) {
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String token() {
        return token;
    }

    public boolean hasOperation(String operationId) {
        return OPERATIONS.contains(operationId);
    }
}
