// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.core;

import java.security.SecureRandom;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ApiClient {
    private static final HttpClient HTTP = HttpClient.newHttpClient();
    private static final SecureRandom RANDOM = new SecureRandom();
    public static final String LAYER = "core";
    public static final String TITLE = "KuberCloud ANI Core API";
    public static final String VERSION = "1.0.0";
    public static final String SERVER_URL = "https://{host}/api/v1";
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listAPIKeys",
        "createAPIKey",
        "revokeAPIKey",
        "logout",
        "beginOIDCLogin",
        "postAuthRefresh",
        "completeOIDCLogin",
        "getBranding",
        "listStorageBuckets",
        "createStorageBucket",
        "listEncryptionKeys",
        "createEncryptionKey",
        "deleteEncryptionKey",
        "getEncryptionKey",
        "revokeEncryptionKey",
        "rotateEncryptionKey",
        "sealEncryptionObject",
        "createEncryptionUnsealToken",
        "listStorageFilesystems",
        "createStorageFilesystem",
        "deleteStorageFilesystem",
        "getStorageFilesystem",
        "listFilesystemMountTargets",
        "listGPUInventory",
        "getGPUOccupancy",
        "listGPUSchedulingQueues",
        "createGPUSchedulingQueue",
        "deleteGPUSchedulingQueue",
        "getGPUSchedulingQueue",
        "updateGPUSchedulingQueue",
        "liveness",
        "getInstanceOperation",
        "listInstances",
        "createInstance",
        "getInstance",
        "createInstanceConsoleSession",
        "listInstanceEvents",
        "createInstanceExecSession",
        "applyInstanceLifecycle",
        "listInstanceLogs",
        "getInstanceMetrics",
        "listInstanceOperations",
        "listInstanceSecurityEvents",
        "listK8sClusters",
        "createK8sCluster",
        "deleteK8sCluster",
        "getK8sCluster",
        "getK8sClusterKubeconfig",
        "listK8sClusterNodePools",
        "createK8sClusterNodePool",
        "deleteK8sClusterNodePool",
        "getK8sClusterNodePool",
        "updateK8sClusterNodePool",
        "proxyK8sClusterAPI",
        "upgradeK8sCluster",
        "listK8sClusterWorkloads",
        "reportTokenUsage",
        "getMeteringUsage",
        "getPlatformMeteringUsage",
        "listNetworkLoadBalancers",
        "createNetworkLoadBalancer",
        "deleteNetworkLoadBalancer",
        "getNetworkLoadBalancer",
        "listNetworkRoutes",
        "createNetworkRoute",
        "listNetworkSecurityGroups",
        "createNetworkSecurityGroup",
        "deleteNetworkSecurityGroup",
        "getNetworkSecurityGroup",
        "listNetworkSubnets",
        "createNetworkSubnet",
        "deleteNetworkSubnet",
        "getNetworkSubnet",
        "listNetworkVPCs",
        "createNetworkVPC",
        "deleteNetworkVPC",
        "getNetworkVPC",
        "listStorageObjects",
        "createStorageObject",
        "uploadStorageObject",
        "deleteStorageObject",
        "getStorageObject",
        "downloadStorageObject",
        "listObservabilityAlertRules",
        "createObservabilityAlertRule",
        "deleteObservabilityAlertRule",
        "getObservabilityAlertRule",
        "updateObservabilityAlertRule",
        "queryObservability",
        "queryRangeObservability",
        "readiness",
        "getRegistryImageScanResult",
        "listRegistryProjects",
        "createRegistryProject",
        "createRegistryProjectPullSecret",
        "listRegistryRepositories",
        "listRegistryArtifacts",
        "setRegistryRepositoryPermission",
        "getRegistryProjectScanReport",
        "listSandboxTemplates",
        "listSecrets",
        "createSecret",
        "deleteSecret",
        "getSecret",
        "bindSecret",
        "getTasksTaskId",
        "listVectorStores",
        "createVectorStore",
        "deleteVectorStore",
        "getVectorStore",
        "insertVectorStoreDocuments",
        "searchVectorStore",
        "listStorageVolumes",
        "createStorageVolume",
        "deleteStorageVolume",
        "getStorageVolume",
        "listVolumeSnapshots",
        "createVolumeSnapshot"
    ));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList(
        "GET /auth/api-keys",
        "POST /auth/api-keys",
        "DELETE /auth/api-keys/{key_id}",
        "POST /auth/logout",
        "POST /auth/oidc/begin",
        "POST /auth/refresh",
        "POST /auth/token",
        "GET /branding",
        "GET /buckets",
        "POST /buckets",
        "GET /encryption/keys",
        "POST /encryption/keys",
        "DELETE /encryption/keys/{key_id}",
        "GET /encryption/keys/{key_id}",
        "POST /encryption/keys/{key_id}/revoke",
        "POST /encryption/keys/{key_id}/rotate",
        "POST /encryption/seal",
        "POST /encryption/unseal-token",
        "GET /filesystems",
        "POST /filesystems",
        "DELETE /filesystems/{filesystem_id}",
        "GET /filesystems/{filesystem_id}",
        "GET /filesystems/{filesystem_id}/mount-targets",
        "GET /gpu-inventory",
        "GET /gpu-inventory/occupancy",
        "GET /gpu-scheduling/queues",
        "POST /gpu-scheduling/queues",
        "DELETE /gpu-scheduling/queues/{queue_id}",
        "GET /gpu-scheduling/queues/{queue_id}",
        "PATCH /gpu-scheduling/queues/{queue_id}",
        "GET /healthz",
        "GET /instance-operations/{operation_id}",
        "GET /instances",
        "POST /instances",
        "GET /instances/{instance_id}",
        "POST /instances/{instance_id}/console",
        "GET /instances/{instance_id}/events",
        "POST /instances/{instance_id}/exec",
        "POST /instances/{instance_id}/lifecycle",
        "GET /instances/{instance_id}/logs",
        "GET /instances/{instance_id}/metrics",
        "GET /instances/{instance_id}/operations",
        "GET /instances/{instance_id}/security-events",
        "GET /k8s-clusters",
        "POST /k8s-clusters",
        "DELETE /k8s-clusters/{cluster_id}",
        "GET /k8s-clusters/{cluster_id}",
        "GET /k8s-clusters/{cluster_id}/kubeconfig",
        "GET /k8s-clusters/{cluster_id}/node-pools",
        "POST /k8s-clusters/{cluster_id}/node-pools",
        "DELETE /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
        "GET /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
        "PATCH /k8s-clusters/{cluster_id}/node-pools/{node_pool_id}",
        "POST /k8s-clusters/{cluster_id}/proxy",
        "POST /k8s-clusters/{cluster_id}/upgrade",
        "GET /k8s-clusters/{cluster_id}/workloads",
        "POST /metering/token-usage",
        "GET /metering/usage",
        "GET /metering/usage/platform",
        "GET /networks/load-balancers",
        "POST /networks/load-balancers",
        "DELETE /networks/load-balancers/{load_balancer_id}",
        "GET /networks/load-balancers/{load_balancer_id}",
        "GET /networks/routes",
        "POST /networks/routes",
        "GET /networks/security-groups",
        "POST /networks/security-groups",
        "DELETE /networks/security-groups/{security_group_id}",
        "GET /networks/security-groups/{security_group_id}",
        "GET /networks/subnets",
        "POST /networks/subnets",
        "DELETE /networks/subnets/{subnet_id}",
        "GET /networks/subnets/{subnet_id}",
        "GET /networks/vpcs",
        "POST /networks/vpcs",
        "DELETE /networks/vpcs/{vpc_id}",
        "GET /networks/vpcs/{vpc_id}",
        "GET /objects",
        "POST /objects",
        "POST /objects/upload",
        "DELETE /objects/{object_id}",
        "GET /objects/{object_id}",
        "GET /objects/{object_id}/download",
        "GET /observability/alert-rules",
        "POST /observability/alert-rules",
        "DELETE /observability/alert-rules/{rule_id}",
        "GET /observability/alert-rules/{rule_id}",
        "PATCH /observability/alert-rules/{rule_id}",
        "GET /observability/query",
        "GET /observability/query_range",
        "GET /readyz",
        "GET /registry/images/scan-result",
        "GET /registry/projects",
        "POST /registry/projects",
        "POST /registry/projects/{project}/pull-secret",
        "GET /registry/projects/{project}/repositories",
        "GET /registry/projects/{project}/repositories/{repository}/artifacts",
        "POST /registry/projects/{project}/repositories/{repository}/permissions",
        "GET /registry/projects/{project}/scan-report",
        "GET /sandbox-templates",
        "GET /secrets",
        "POST /secrets",
        "DELETE /secrets/{secret_id}",
        "GET /secrets/{secret_id}",
        "POST /secrets/{secret_id}/bindings",
        "GET /tasks/{task_id}",
        "GET /vector-stores",
        "POST /vector-stores",
        "DELETE /vector-stores/{vector_store_id}",
        "GET /vector-stores/{vector_store_id}",
        "POST /vector-stores/{vector_store_id}/documents",
        "POST /vector-stores/{vector_store_id}/search",
        "GET /volumes",
        "POST /volumes",
        "DELETE /volumes/{volume_id}",
        "GET /volumes/{volume_id}",
        "GET /volumes/{volume_id}/snapshots",
        "POST /volumes/{volume_id}/snapshots"
    ));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList(
        "APIKeyInfo",
        "AsyncTask",
        "BeginOIDCLoginRequest",
        "BeginOIDCLoginResponse",
        "CompleteOIDCLoginRequest",
        "CoreDevProfileInfo",
        "CreateAPIKeyRequest",
        "CreateAPIKeyResponse",
        "CreateContainerInstanceConfig",
        "CreateGPUContainerInstanceConfig",
        "CreateInstanceConsoleSessionRequest",
        "CreateInstanceExecSessionRequest",
        "CreateInstanceRequest",
        "CreateInstanceResponse",
        "CreateNetworkLoadBalancerRequest",
        "CreateNetworkRouteRequest",
        "CreateNetworkSecurityGroupRequest",
        "CreateNetworkSubnetRequest",
        "CreateNetworkVPCRequest",
        "CreateObservabilityAlertRuleRequest",
        "CreateRegistryProjectRequest",
        "CreateRegistryPullSecretRequest",
        "CreateStorageBucketRequest",
        "CreateStorageFilesystemRequest",
        "CreateStorageObjectRequest",
        "CreateStorageVolumeRequest",
        "CreateVMInstanceConfig",
        "CreateVectorStoreRequest",
        "CreateVolumeSnapshotRequest",
        "CursorPage",
        "EncryptionKey",
        "EncryptionKeyCreateRequest",
        "EncryptionKeyListResponse",
        "EncryptionKeyRevokeRequest",
        "EncryptionKeyRotateRequest",
        "EncryptionKeyRotationResponse",
        "EncryptionSealRequest",
        "EncryptionSealResponse",
        "EncryptionUnsealTokenRequest",
        "EncryptionUnsealTokenResponse",
        "ErrorResponse",
        "FilesystemMountTarget",
        "FilesystemMountTargetListResponse",
        "GPUInventoryListResponse",
        "GPUInventoryRecord",
        "GPUOccupancyStats",
        "GPUSchedulingQueue",
        "GPUSchedulingQueueCreateRequest",
        "GPUSchedulingQueueListResponse",
        "GPUSchedulingQueueUpdateRequest",
        "HealthCheck",
        "InstanceConsoleSession",
        "InstanceEvent",
        "InstanceEventListResponse",
        "InstanceExecSession",
        "InstanceLifecycleRequest",
        "InstanceLifecycleResponse",
        "InstanceListResponse",
        "InstanceLogEntry",
        "InstanceLogListResponse",
        "InstanceMetrics",
        "InstanceOperation",
        "InstanceRecord",
        "InstanceSecurityEvent",
        "InstanceSecurityEventListResponse",
        "K8sCluster",
        "K8sClusterCreateRequest",
        "K8sClusterKubeconfig",
        "K8sClusterListResponse",
        "K8sClusterNodePool",
        "K8sClusterNodePoolCreateRequest",
        "K8sClusterNodePoolGPU",
        "K8sClusterNodePoolListResponse",
        "K8sClusterNodePoolUpdateRequest",
        "K8sClusterProxyRequest",
        "K8sClusterProxyResponse",
        "K8sClusterUpgradeRequest",
        "K8sClusterWorkload",
        "K8sClusterWorkloadListResponse",
        "ListAPIKeysResponse",
        "LogoutRequest",
        "MeteringUsageRecord",
        "MeteringUsageResponse",
        "NetworkLoadBalancer",
        "NetworkLoadBalancerListResponse",
        "NetworkLoadBalancerListener",
        "NetworkResourceState",
        "NetworkRoute",
        "NetworkRouteListResponse",
        "NetworkSecurityGroup",
        "NetworkSecurityGroupListResponse",
        "NetworkSecurityGroupRule",
        "NetworkSubnet",
        "NetworkSubnetListResponse",
        "NetworkVPC",
        "NetworkVPCListResponse",
        "ObservabilityAlertRule",
        "ObservabilityAlertRuleListResponse",
        "ObservabilityQueryResponse",
        "ObservabilityRangeQueryResponse",
        "RefreshAccessTokenRequest",
        "RefreshAccessTokenResponse",
        "RegistryArtifact",
        "RegistryArtifactListResponse",
        "RegistryPermission",
        "RegistryProject",
        "RegistryProjectListResponse",
        "RegistryProjectScanReport",
        "RegistryPullSecret",
        "RegistryRepository",
        "RegistryRepositoryListResponse",
        "RegistryScanResult",
        "ReportTokenUsageRequest",
        "RevokeStatusResponse",
        "SandboxConfig",
        "SandboxInstanceStatus",
        "SandboxNetworkEgressPolicy",
        "SandboxTemplate",
        "SandboxTemplateListResponse",
        "Secret",
        "SecretBinding",
        "SecretBindingRequest",
        "SecretCreateRequest",
        "SecretListResponse",
        "SetRegistryPermissionRequest",
        "StorageBucketListResponse",
        "StorageBucketRecord",
        "StorageFilesystem",
        "StorageFilesystemListResponse",
        "StorageObject",
        "StorageObjectDownloadInfo",
        "StorageObjectListResponse",
        "StorageObjectUploadRequest",
        "StorageObjectUploadResponse",
        "StorageResourceState",
        "StorageVolume",
        "StorageVolumeListResponse",
        "TokenPairResponse",
        "TokenUsageReport",
        "UpdateObservabilityAlertRuleRequest",
        "VectorStore",
        "VectorStoreDocumentInsertRequest",
        "VectorStoreDocumentInsertResponse",
        "VectorStoreListResponse",
        "VectorStoreSearchHit",
        "VectorStoreSearchRequest",
        "VectorStoreSearchResponse",
        "VectorStoreState",
        "VolumeSnapshotListResponse",
        "VolumeSnapshotRecord",
        "WorkloadIdentityBinding"
    ));
    public static final List<String> IDEMPOTENCY_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "createStorageBucket",
        "createEncryptionKey",
        "revokeEncryptionKey",
        "rotateEncryptionKey",
        "sealEncryptionObject",
        "createStorageFilesystem",
        "createInstance",
        "createInstanceExecSession",
        "applyInstanceLifecycle",
        "createK8sCluster",
        "createK8sClusterNodePool",
        "updateK8sClusterNodePool",
        "proxyK8sClusterAPI",
        "upgradeK8sCluster",
        "reportTokenUsage",
        "createNetworkLoadBalancer",
        "createNetworkRoute",
        "createNetworkSecurityGroup",
        "createNetworkSubnet",
        "createNetworkVPC",
        "createStorageObject",
        "uploadStorageObject",
        "createObservabilityAlertRule",
        "updateObservabilityAlertRule",
        "createRegistryProject",
        "createRegistryProjectPullSecret",
        "setRegistryRepositoryPermission",
        "createSecret",
        "createVectorStore",
        "insertVectorStoreDocuments",
        "createStorageVolume",
        "createVolumeSnapshot"
    ));
    public static final List<String> CURSOR_PAGINATION_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listStorageBuckets",
        "listEncryptionKeys",
        "listStorageFilesystems",
        "listFilesystemMountTargets",
        "listGPUInventory",
        "listInstances",
        "listInstanceLogs",
        "listInstanceOperations",
        "listK8sClusters",
        "listK8sClusterWorkloads",
        "listNetworkLoadBalancers",
        "listNetworkRoutes",
        "listNetworkSecurityGroups",
        "listNetworkSubnets",
        "listNetworkVPCs",
        "listStorageObjects",
        "listObservabilityAlertRules",
        "listRegistryProjects",
        "listRegistryRepositories",
        "listRegistryArtifacts",
        "listSandboxTemplates",
        "listSecrets",
        "listVectorStores",
        "listStorageVolumes",
        "listVolumeSnapshots"
    ));
    public static final List<String> ERROR_CODES = Collections.unmodifiableList(Arrays.asList(
        "BAD_REQUEST",
        "CONFLICT",
        "FORBIDDEN",
        "INTERNAL_ERROR",
        "NOT_FOUND",
        "NOT_IMPLEMENTED",
        "PRECONDITION_FAILED",
        "RATE_LIMIT_EXCEEDED",
        "UNAUTHORIZED"
    ));

    private final String baseUrl;
    private final String token;

    public static final class APIError {
        private final String code;
        private final String message;
        private final String requestId;
        private final Map<String, Object> details;

        public APIError(String code, String message, String requestId, Map<String, Object> details) {
            this.code = code;
            this.message = message;
            this.requestId = requestId;
            this.details = details == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(details));
        }

        public String code() {
            return code;
        }

        public String message() {
            return message;
        }

        public String requestId() {
            return requestId;
        }

        public Map<String, Object> details() {
            return details;
        }
    }

    public static final class APIException extends Exception {
        private final APIError apiError;

        public APIException(APIError apiError) {
            super(apiError == null ? "" : apiError.code() + ": " + apiError.message());
            this.apiError = apiError;
        }

        public APIError apiError() {
            return apiError;
        }
    }

    public static final class RequestOptions {
        private final String bodyJson;
        private final Map<String, String> params;
        private final Map<String, String> headers;

        public RequestOptions(String bodyJson, Map<String, String> params, Map<String, String> headers) {
            this.bodyJson = bodyJson;
            this.params = params == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(params));
            this.headers = headers == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(headers));
        }

        public String bodyJson() {
            return bodyJson;
        }

        public Map<String, String> params() {
            return params;
        }

        public Map<String, String> headers() {
            return headers;
        }
    }

    public ApiClient(String baseUrl, String token) {
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String token() {
        return token;
    }

    public boolean hasOperation(String operationId) {
        return OPERATIONS.contains(operationId);
    }

    public String request(String method, String path, RequestOptions options) throws IOException, InterruptedException, APIException {
        RequestOptions opts = options == null ? new RequestOptions(null, null, null) : options;
        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(requestUrl(path, opts.params())))
                .header("Accept", "application/json");
        if (token != null && !token.isEmpty()) {
            builder.header("Authorization", "Bearer " + token);
        }
        for (Map.Entry<String, String> entry : opts.headers().entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        String upperMethod = method == null ? "GET" : method.toUpperCase();
        if (opts.bodyJson() == null) {
            builder.method(upperMethod, HttpRequest.BodyPublishers.noBody());
        } else {
            builder.header("Content-Type", "application/json");
            builder.method(upperMethod, HttpRequest.BodyPublishers.ofString(opts.bodyJson()));
        }
        HttpResponse<String> response = HTTP.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() >= 400) {
            throw new APIException(parseAPIError(response.body(), response.statusCode()));
        }
        return response.body();
    }

    private String requestUrl(String path, Map<String, String> params) {
        String base = baseUrl.replaceAll("/+$", "");
        String relative = path == null || path.isEmpty() ? "/" : "/" + path.replaceAll("^/+", "");
        if (params == null || params.isEmpty()) {
            return base + relative;
        }
        StringJoiner query = new StringJoiner("&");
        for (Map.Entry<String, String> entry : params.entrySet()) {
            if (entry.getValue() != null && !entry.getValue().isEmpty()) {
                query.add(URLEncoder.encode(entry.getKey(), StandardCharsets.UTF_8) + "=" + URLEncoder.encode(entry.getValue(), StandardCharsets.UTF_8));
            }
        }
        String encoded = query.toString();
        return encoded.isEmpty() ? base + relative : base + relative + "?" + encoded;
    }

    private static APIError parseAPIError(String body, int statusCode) {
        String code = jsonString(body, "code");
        String message = jsonString(body, "message");
        String requestId = jsonString(body, "request_id");
        if (code == null || code.isEmpty()) {
            code = "HTTP_" + statusCode;
        }
        if (message == null || message.isEmpty()) {
            message = "ANI API request failed";
        }
        return new APIError(code, message, requestId == null ? "" : requestId, null);
    }

    private static String jsonString(String body, String field) {
        if (body == null) {
            return "";
        }
        Pattern pattern = Pattern.compile("\\\"" + Pattern.quote(field) + "\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");
        Matcher matcher = pattern.matcher(body);
        return matcher.find() ? matcher.group(1) : "";
    }

    public static String newIdempotencyKey(String prefix) {
        String safePrefix = (prefix == null || prefix.isEmpty()) ? "ani" : prefix;
        byte[] random = new byte[16];
        RANDOM.nextBytes(random);
        StringBuilder encoded = new StringBuilder(random.length * 2);
        for (byte value : random) {
            encoded.append(String.format("%02x", value & 0xff));
        }
        return safePrefix + "_" + encoded;
    }

    public static Map<String, Object> withIdempotencyKey(Map<String, Object> body, String key) {
        Map<String, Object> payload = new HashMap<>();
        if (body != null) {
            payload.putAll(body);
        }
        payload.put("idempotency_key", (key == null || key.isEmpty()) ? newIdempotencyKey("ani") : key);
        return payload;
    }

    public static Map<String, String> cursorParams(int limit, String cursor) {
        Map<String, String> params = new HashMap<>();
        if (limit > 0) {
            params.put("limit", Integer.toString(limit));
        }
        if (cursor != null && !cursor.isEmpty()) {
            params.put("cursor", cursor);
        }
        return params;
    }

    public static boolean isAPIErrorCode(String code) {
        return ERROR_CODES.contains(code);
    }

    public static APIError apiError(String code, String message, String requestId, Map<String, Object> details) {
        return new APIError(code, message, requestId, details);
    }
}
