// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.core;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public final class ApiClient {
    public static final String LAYER = "core";
    public static final String TITLE = "KuberCloud ANI Core API";
    public static final String VERSION = "1.0.0";
    public static final String SERVER_URL = "https://{host}/api/v1";
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listAPIKeys",
        "createAPIKey",
        "revokeAPIKey",
        "logout",
        "beginOIDCLogin",
        "postAuthRefresh",
        "completeOIDCLogin",
        "getBranding",
        "listStorageFilesystems",
        "createStorageFilesystem",
        "deleteStorageFilesystem",
        "getStorageFilesystem",
        "liveness",
        "getInstanceOperation",
        "listInstances",
        "createInstance",
        "getInstance",
        "createInstanceConsoleSession",
        "applyInstanceLifecycle",
        "listInstanceOperations",
        "getMeteringUsage",
        "listNetworkLoadBalancers",
        "createNetworkLoadBalancer",
        "deleteNetworkLoadBalancer",
        "getNetworkLoadBalancer",
        "listNetworkSecurityGroups",
        "createNetworkSecurityGroup",
        "deleteNetworkSecurityGroup",
        "getNetworkSecurityGroup",
        "listNetworkSubnets",
        "createNetworkSubnet",
        "deleteNetworkSubnet",
        "getNetworkSubnet",
        "listNetworkVPCs",
        "createNetworkVPC",
        "deleteNetworkVPC",
        "getNetworkVPC",
        "listStorageObjects",
        "createStorageObject",
        "deleteStorageObject",
        "getStorageObject",
        "readiness",
        "getTasksTaskId",
        "listVectorStores",
        "createVectorStore",
        "deleteVectorStore",
        "getVectorStore",
        "searchVectorStore",
        "listStorageVolumes",
        "createStorageVolume",
        "deleteStorageVolume",
        "getStorageVolume"
    ));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList(
        "GET /auth/api-keys",
        "POST /auth/api-keys",
        "DELETE /auth/api-keys/{key_id}",
        "POST /auth/logout",
        "POST /auth/oidc/begin",
        "POST /auth/refresh",
        "POST /auth/token",
        "GET /branding",
        "GET /filesystems",
        "POST /filesystems",
        "DELETE /filesystems/{filesystem_id}",
        "GET /filesystems/{filesystem_id}",
        "GET /healthz",
        "GET /instance-operations/{operation_id}",
        "GET /instances",
        "POST /instances",
        "GET /instances/{instance_id}",
        "POST /instances/{instance_id}/console",
        "POST /instances/{instance_id}/lifecycle",
        "GET /instances/{instance_id}/operations",
        "GET /metering/usage",
        "GET /networks/load-balancers",
        "POST /networks/load-balancers",
        "DELETE /networks/load-balancers/{load_balancer_id}",
        "GET /networks/load-balancers/{load_balancer_id}",
        "GET /networks/security-groups",
        "POST /networks/security-groups",
        "DELETE /networks/security-groups/{security_group_id}",
        "GET /networks/security-groups/{security_group_id}",
        "GET /networks/subnets",
        "POST /networks/subnets",
        "DELETE /networks/subnets/{subnet_id}",
        "GET /networks/subnets/{subnet_id}",
        "GET /networks/vpcs",
        "POST /networks/vpcs",
        "DELETE /networks/vpcs/{vpc_id}",
        "GET /networks/vpcs/{vpc_id}",
        "GET /objects",
        "POST /objects",
        "DELETE /objects/{object_id}",
        "GET /objects/{object_id}",
        "GET /readyz",
        "GET /tasks/{task_id}",
        "GET /vector-stores",
        "POST /vector-stores",
        "DELETE /vector-stores/{vector_store_id}",
        "GET /vector-stores/{vector_store_id}",
        "POST /vector-stores/{vector_store_id}/search",
        "GET /volumes",
        "POST /volumes",
        "DELETE /volumes/{volume_id}",
        "GET /volumes/{volume_id}"
    ));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList(
        "APIKeyInfo",
        "AsyncTask",
        "BeginOIDCLoginRequest",
        "BeginOIDCLoginResponse",
        "CompleteOIDCLoginRequest",
        "CoreDevProfileInfo",
        "CreateAPIKeyRequest",
        "CreateAPIKeyResponse",
        "CreateInstanceConsoleSessionRequest",
        "CreateInstanceRequest",
        "CreateInstanceResponse",
        "CreateNetworkLoadBalancerRequest",
        "CreateNetworkSecurityGroupRequest",
        "CreateNetworkSubnetRequest",
        "CreateNetworkVPCRequest",
        "CreateStorageFilesystemRequest",
        "CreateStorageObjectRequest",
        "CreateStorageVolumeRequest",
        "CreateVectorStoreRequest",
        "CursorPage",
        "ErrorResponse",
        "HealthCheck",
        "InstanceConsoleSession",
        "InstanceLifecycleRequest",
        "InstanceLifecycleResponse",
        "InstanceListResponse",
        "InstanceOperation",
        "InstanceRecord",
        "ListAPIKeysResponse",
        "LogoutRequest",
        "NetworkLoadBalancer",
        "NetworkLoadBalancerListResponse",
        "NetworkLoadBalancerListener",
        "NetworkResourceState",
        "NetworkSecurityGroup",
        "NetworkSecurityGroupListResponse",
        "NetworkSecurityGroupRule",
        "NetworkSubnet",
        "NetworkSubnetListResponse",
        "NetworkVPC",
        "NetworkVPCListResponse",
        "RefreshAccessTokenRequest",
        "RefreshAccessTokenResponse",
        "RevokeStatusResponse",
        "StorageFilesystem",
        "StorageFilesystemListResponse",
        "StorageObject",
        "StorageObjectListResponse",
        "StorageResourceState",
        "StorageVolume",
        "StorageVolumeListResponse",
        "TokenPairResponse",
        "VectorStore",
        "VectorStoreListResponse",
        "VectorStoreSearchHit",
        "VectorStoreSearchRequest",
        "VectorStoreSearchResponse",
        "VectorStoreState",
        "WorkloadIdentityBinding"
    ));

    private final String baseUrl;
    private final String token;

    public ApiClient(String baseUrl, String token) {
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String token() {
        return token;
    }

    public boolean hasOperation(String operationId) {
        return OPERATIONS.contains(operationId);
    }
}
