// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.core;

public final class Smoke {
    public static void main(String[] args) {
        ApiClient client = new ApiClient("", "token");
        if (client.baseUrl().isEmpty() || ApiClient.TITLE.isEmpty() || ApiClient.VERSION.isEmpty()) {
            throw new IllegalStateException("invalid SDK metadata");
        }
        if (ApiClient.SCHEMAS.isEmpty()) {
            throw new IllegalStateException("expected generated schemas");
        }
        if (ApiClient.OPERATIONS.isEmpty()) {
            throw new IllegalStateException("expected generated operations");
        }
        if (!client.hasOperation("listAPIKeys")) {
            throw new IllegalStateException("missing expected operation");
        }

        System.out.println("core java SDK alpha smoke ok");
    }
}
